### ISSUE TITLE
Cannot retrieve modulus from PKCS#8 private key

### ISSUE THREAD

**Issue by gringus** [wbond/asn1crypto#101]
While writing some internal tool which need to extract modulus from certificates/private keys I run into some problems. I generate a new RSA private key:
```
openssl genpkey -algorithm RSA -out test.pem
```
Command:
```
openssl rsa -in test.pem -noout -modulus
```
returns modulus of the key. Unfortunately trying to run:
```
from asn1crypto import keys, pem

with open('test.pem', 'rb') as f:
    type_name, headers, der_bytes = pem.unarmor(f.read())
    object = keys.RSAPrivateKey.load(der_bytes)
    print(object['modulus'].native)
```
throws the following error:
```
ValueError: Field "private_exponent" is missing from structure
    while parsing asn1crypto.keys.RSAPrivateKey
```
This seems to be affecting only PKCS#8 keys (`BEGIN PRIVATE KEY` tag) but not PKCS#1 keys (`BEGIN RSA PRIVATE KEY` tag), so:
```
openssl genrsa -out test.pem
```
does not cause any problems. This is with **asn1crypto 0.24** and **OpenSSL 1.0.2o**.

**Comment by joernheissler** [comment]
Use `keys.PrivateKeyInfo`

**Comment by wbond** [comment]
@gringus As @joernheissler has pointed out, `keys.PrivateKeyInfo` is the ASN.1 structure for `PRIVATE KEY` PEM files. `keys.RSAPrivateKey` is for `RSA PRIVATE KEY` PEM files. The former is a general container structure that can contain an RSA, DSA or ECDSA private key.

**Comment by wbond** [comment]
Loading is done lazily, for performance reasons. It did fail as soon as you tried to parse the entire structure. At the top-most level, the two structure have the same basic tag, so there isn't an incompatibility until you try parsing the fields.

If you want to ensure loading was successful, call `.native`, which will recursively parse every field of a structure. See https://github.com/wbond/oscrypto/blob/master/oscrypto/keys.py#L172-L286 for an example of loading private keys from a user, where they may not know what they have.
