### ISSUE TITLE
Add typing

### ISSUE THREAD

**Issue by ysangkok** [wbond/asn1crypto#106]
Would you accept a pull request to add pyi (PEP 561) typing stubs?

**Comment by wbond** [comment]
I would love to add typing info. The one thing holding me back is that I want it to be full Python 3.6 annotations (not comments), so to keep compatibility with older versions, I wish there was a tool that would strip the annotations for releases on old versions.

Do you know of such a thing?

**Comment by ysangkok** [comment]
Yes: https://pypi.org/project/strip-hints/

**Comment by wbond** [comment]
Looks perfect. I presume there would need to be two packages on pypi - one for Python 2.6-3.5 with no annotations and 3.6 with full annotations, right?

**Comment by ysangkok** [comment]
Since you only need syntax support, I think it would be enough to have a Python 2.6-2.7 package and a Python 3+. [PEP 3107](https://www.python.org/dev/peps/pep-3107/) is implemented in Python 3.

**Comment by ysangkok** [comment]
Well since it would be nice to install the annotation so that type checking works, you are right, Python 3.6 should just get the files unchanged, and earlier versions could just get all the type information stripped. Sorry for the confusion. 

Now that I have tried adding typing stubs to dnspython, it looks to me like being able to annotate types on fields and variables comes in handy, because otherwise you might need to refactor quite a bit. But I don't think it's very bad if it doesn't type check before 3.6.

**Comment by ysangkok** [comment]
So, would you accept a pull request that added Python 3.6 types if I can successfully remove them again with strip-types and run the tests Python 2.7?

**Comment by ysangkok** [comment]
Closing because I think adding typing in Python defeats the purpose of using Python.

**Comment by jimlast** [comment]
Hi Will,

Is there any way this can be revisited, or a solution documented? We use mypy extensively for type checking in production code, and the asn1crypto, oscrypto, etc packages all require `# type ignore` annotations to keey MyPy happy.

I disagree that type checking is antithetical to Python. There's a reason why type support has been around since 2015. Python has never required type checking, but it's extremely helpful in flushing out runtime errors before you get to runtime.

**Comment by wbond** [comment]
I have no opposition to this, just not the time to work on it, currently.

Is this for a personal project, or something that your company may be interested in sponsoring?
