### ISSUE TITLE
Add pkcs12_sha1_rc4_128 to EncryptionAlgorithmId

### ISSUE THREAD

**Issue by luckylud** [wbond/asn1crypto#108]
Hi all,

I use asn1crypto for one project and I want to submit one pull request to add pkcs12_sha1_rc4_128   EncryptionAlgorithmId in asn1crypto/algos.py

See : https://github.com/luckylud/asn1crypto/commit/6e0ddd673584d7855519d2589f8222c8c02da2b7

Thanks

**Comment by wbond** [comment]
Best to submit this as a pull request, then comments can be made.

My main question would be what RFC defines this OID.

**Comment by wbond** [comment]
See #110
