### ISSUE TITLE
Should KeyTransRecipientInfo use a different Algorithm OID->parameter class map?

### ISSUE THREAD

**Issue by wiml** [wbond/asn1crypto#115]
https://github.com/wbond/asn1crypto/blob/98d23f5fcce5d3ed3296bac77aef487b6245807a/asn1crypto/cms.py#L673

Right now, `KeyTransRecipientInfo`'s `key_encryption_algorithm` field is parsed as a `KeyEncryptionAlgorithm`. However that spec's mapping is mostly for key "wrapping" (transporting a key using a symmetric key) while KTRI is used for transporting a key using an asymmetric key. The algorithms used in KTRI are typically `rsaes_pkcs1v15` or `rsaes_oaep`.

It doesn't look like there is already a sequence type in asn1crypto which has mappings for both `rsaes_pkcs1v15` and `rsaes_oaep`, but maybe it would make sense to combine all of the AlgorithmIdentifier specs for encryption algorithms (symmetric or asymmetric or "wrapping") into one?

(It happens that the RSA key type and the RSAES-PKCS1v15 algorithm have the same OID, and neither requires parameters, so the existing mapping works okay for RSA, although I think it would be clearer to use the `rsaes_pkcs1v15` name. However, RSA-OAEP does have parameters, and without a mapping for it, it's difficult to work with RSA-OAEP-encrypted data.)

**Comment by wbond** [comment]
I haven't worked with CMS very much, other than PKCS#12, so I'm not going to have much insight into this.

I think it makes sense to add whatever algorithms are actually used in KTRI to `KeyEncryptionAlgorithm`. We can handle deprecating the usage of `rsa` and instead using `rashes_pkcs1v15` by providing a `_reverse_map` like in https://github.com/wbond/asn1crypto/blob/aa5b306/asn1crypto/algos.py#L265-L289 that points the OID to the preferred name.

**Comment by LuNoX** [comment]
So I've been running into this exact issue: asn1crypto not being able to parse RSAES-OAEP-params. 
Do you have any advice for best practice until you implement it?

**Comment by wbond** [comment]
No, I don't. I don't really have much time for this project ATM.

It sounds like someone who is using these should figure out what makes sense, provide some links to docs showing why they are to be included and send a PR.

**Comment by wbond** [comment]
From looking at rfc5652, it indicates that KeyEncryptionAlgorithmIdentifier (which asn1crypto calls KeyEncryptionAlgorithmId) can be used for key agreement, symmetric wrapping, etc. I think because of this we should add the RSA OIDs as @luckylud partially did in #111.

**Comment by wbond** [comment]
I've added support for RSA OAEP in KeyEncryptionAlgorithm with 850c0c0d5732c236ca384e2c44c408a9c0f93298.
