### ISSUE TITLE
Certificate status lost while parsing OCSP response

### ISSUE THREAD

**Issue by laurivosandi** [wbond/asn1crypto#117]
Hi,

it seems during the parse information is lost and both "good" and "unknown" states are mapped to None?
https://github.com/wbond/asn1crypto/blob/master/asn1crypto/ocsp.py#L329

Also I think all three cases should be covered in the unit test, currently there is no checks for certificate status there.

Code snippet I used for testing:

```
from asn1crypto import ocsp, pem, x509
import requests

certificate_buf = b"""
-----BEGIN CERTIFICATE-----
MIIF5zCCA8+gAwIBAgIQayc3fL+OmQtaHqUpJIKeujANBgkqhkiG9w0BAQsFADBj
MQswCQYDVQQGEwJFRTEiMCAGA1UECgwZQVMgU2VydGlmaXRzZWVyaW1pc2tlc2t1
czEXMBUGA1UEYQwOTlRSRUUtMTA3NDcwMTMxFzAVBgNVBAMMDkVTVEVJRC1TSyAy
MDE1MB4XDTE3MTEyOTEyMTY0MVoXDTE5MTEwNzIxNTk1OVowgZ8xCzAJBgNVBAYT
AkVFMRkwFwYDVQQKDBBFU1RFSUQgKERJR0ktSUQpMRcwFQYDVQQLDA5hdXRoZW50
aWNhdGlvbjEjMCEGA1UEAwwaVsOVU0FOREksTEFVUkksMzg4MTAyNDAzNDgxETAP
BgNVBAQMCFbDlVNBTkRJMQ4wDAYDVQQqDAVMQVVSSTEUMBIGA1UEBRMLMzg4MTAy
NDAzNDgwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAT6OOQmBBJ4fjnmXkCmLeDwcQOx
MtHeSsAbQKcORvWv1Qkw2UewSHag9KIWTdM/XATxtUDBp8tHaI59z+CuOuTJW93/
KGwIEhdOCx1JgqCZm+eH1oBUuvXW/Z3vwNFY80CjggIGMIICAjAJBgNVHRMEAjAA
MA4GA1UdDwEB/wQEAwIDiDBTBgNVHSAETDBKMD4GCSsGAQQBzh8BAjAxMC8GCCsG
AQUFBwIBFiNodHRwczovL3d3dy5zay5lZS9yZXBvc2l0b29yaXVtL0NQUzAIBgYE
AI96AQIwIQYDVR0RBBowGIEWbGF1cmkudm9zYW5kaUBlZXN0aS5lZTAdBgNVHQ4E
FgQUH8FQqUGrpoGB6uFNV9Lens3+ipgwIAYDVR0lAQH/BBYwFAYIKwYBBQUHAwIG
CCsGAQUFBwMEMB8GA1UdIwQYMBaAFLOriLyZ1WKkhSoIzbQdcjuDckdRMGEGCCsG
AQUFBwEDBFUwUzBRBgYEAI5GAQUwRzBFFj9odHRwczovL3NrLmVlL2VuL3JlcG9z
aXRvcnkvY29uZGl0aW9ucy1mb3ItdXNlLW9mLWNlcnRpZmljYXRlcy8TAkVOMGoG
CCsGAQUFBwEBBF4wXDAnBggrBgEFBQcwAYYbaHR0cDovL2FpYS5zay5lZS9lc3Rl
aWQyMDE1MDEGCCsGAQUFBzAChiVodHRwOi8vYy5zay5lZS9FU1RFSUQtU0tfMjAx
NS5kZXIuY3J0MDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly93d3cuc2suZWUvY3Js
cy9lc3RlaWQvZXN0ZWlkMjAxNS5jcmwwDQYJKoZIhvcNAQELBQADggIBAFBuNJvm
1RPqDp81upsmjYUXe86z+6iWQOLTF3zvKmj3hwzmp4KkbmDrWvstWFABSkst5A4c
BcgGbDZzdsdAaf1gq4/b9hXnxQ//x9NRnPFZJL1yMl7Qf/y2Z957ZwTJMPntXmlf
BJF3nQbA0w5D8al+/W8esl7BkFdBge7l6gpA2Y+PynwqfB/uYhI+7MQaIiSe33LO
hdlz7DlNnHGa2ahTJu8i4+Ip0j86whP6XBt2vT4WLsfwWoZal5gs7kcsWq0/5a2k
ULQQ363leirkt7kuGnXKOnukxWL3GeBJwo++GxvK/7j5uUbdwtMgkwlyQkdhxSWI
ome6VtqBsh6Tk907P3TCWNwGP0y1UAx6xCHQisjywgOPy9nxCVIxPjMlUXkwSYtl
pyN9guqFx61XV6dPzAPtlOHSFB73hNgqt7ikLHyhI2kUgW5zLVqLEOw2iE6s24AY
jhPjJSgaWC+jDXbE4NuAhe0bj/M2VIKoXCOOl/ZqTM6cjR4xY9yy0bucDE1awqHp
nb0E0V4hvFAeRtOgydG6TxnZjjvRk5oR0CRaMidFtWX+VKVIozaeytVnVhfNU0SG
HccSCfIUQvPI+ukQQ3hOwMQptccpCo9CHXu2KRsVbE3rti0GM/+M9pDqKteu0k6f
1pnshaUqoYBcOOGuFerrVQXsA8meY9Y8qv3r
-----END CERTIFICATE-----
"""
url = "http://ocsp.sk.ee/_proxy"

header, _, certificate_der_bytes = pem.unarmor(certificate_buf)
certificate = x509.Certificate.load(certificate_der_bytes)

print("Subject is:", certificate.subject.native)

buf = ocsp.OCSPRequest({
	"tbs_request": {
		"request_list": [{
			"req_cert": {
				"serial_number":  certificate.serial_number,
				'hash_algorithm': {
				    'algorithm': "sha1"
				},
        'issuer_name_hash': certificate.subject.sha1,
				'issuer_key_hash': certificate.public_key.sha1,
			},
		}],
	}
}).dump()

r = requests.post(url, data=buf, headers={"Content-Type":"application/ocsp-request"})
response = ocsp.OCSPResponse.load(r.content).native["response_bytes"]["response"]
for r in response["tbs_response_data"]["responses"]:
  print("Certificate status is:", r["cert_status"])
```

**Comment by joernheissler** [comment]
The desired info is in the `name` attribute, but `native` doesn't return it. But no idea how to fix that.

```python3
from asn1crypto.ocsp import CertStatus

for x in [
    '8000',
    'a116180f32303138313030333134353334375aa0030a0101',
    '8200',
]:
    status = CertStatus.load(bytes.fromhex(x))
    print(status.name, status.native)

# good None
# revoked OrderedDict([('revocation_time', datetime.datetime(2018, 10, 3, 14, 53, 47, tzinfo=datetime.timezone.utc)), ('revocation_reason', 'key_compromise')])
# unknown None
```

**Comment by wbond** [comment]
It looks like `CertStatus` Is a rather weirdly designed ASN.1 structure. The actual value of good and unknown are both NULL, but their "value" is determined by the chosen alternative.

It may be that we need to revamp how the `Choice` type works when calling `.native`. Currently it returns the native value of the chosen alternative. However, when constructing a `core.Choice`, you have to specify the alternative being used. These should probably made symmetrical, so you can use the `.native` value to construct a new instance.

**Comment by joernheissler** [comment]
That means for above code, `.native` would return one of those?
* `{"good": None}`
* `{"revoked": OrderedDict([('revocation_time', datetime.datetime(2018, 10, 3, 14, 53, 47, tzinfo=datetime.timezone.utc)), ('revocation_reason', 'key_compromise')])}`
* `{"unknown": None}`

That might be a breaking change because right now `.native` returns something else. (I don't mind changing my own software that might depend on this behaviour).

Should the `chosen` attribute change as well? Perhaps it can return a sub class of `Null` like `NotRevoked` or `RevocationUnknown`.
I.e. `Choice._alternatives` must not contain two identical types.
From what I can see, `CertStatus` is currently the only class with duplicate alternatives classes.
`ECDomainParameters` got one `Null` class which could be changed too.

If ambiguity is eliminated, construction of a `Choice` might not require a dict anymore but could **optionally** take a simpler value: `CertStatus(RevocationUnknown())`

Then maybe `.native` can be changed so that not a dict is returned but one of those:
* `NotRevoked`
* `OrderedDict([('revocation_time', datetime.datetime(2018, 10, 3, 14, 53, 47, tzinfo=datetime.timezone.utc)), ('revocation_reason', 'key_compromise')])`
* `RevocationUnknown`

But I guess the whole point of `.native` is to return native types :-))

**Comment by wbond** [comment]
I was thinking about this yesterday. Changing .native for Choice would be a breaking change and not generally helpful.

I think what we may do with this case is override .native and raise an exception indicating that .native is ambiguous. That or override .native to output a sane value, and override the constructor to accept those sane options. The second option would definitely be more user friendly.

**Comment by wbond** [comment]
As of 241dc6f503ff7f6cb99d39fffb9463047d131833, `ocsp.CertStatus().native` will return:

 - `"good"` for when the choice is `"good"`
 - `"unknown"` for when the choice is `"unknown"`
 - `asn1crypto.util.OrderedDict()` for when the choice is `"revoked"`
