### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by ra-kete** [wbond/asn1crypto#119]
The last release, 0.24.0, was published nearly 10 months ago now. Looks like a lot has happened since then. Can we get a new release on PyPI, for those who cannot pull directly from master?

**Comment by joernheissler** [comment]
Would https://github.com/wbond/asn1crypto/pull/99 address your issue?

**Comment by ra-kete** [comment]
This issue isn't about stability concerns but that the build process we use internally doesn't support pulling dependencies from GitHub, only PyPI. So we cannot use any of the recent improvements to asn1crypto unless there is a new PyPI release.

So I believe this other issue is unrelated, unless I'm missing something?

**Comment by joernheissler** [comment]
https://github.com/wbond/asn1crypto/pull/99#issuecomment-399775577
This new release would include the recent (and future) changes.
But I guess it wouldn't hurt to make a 0.25.0 which includes whatever changes are there at the moment.

**Comment by wbond** [comment]
I'd like to do a new release at some point soon, but this is a hobby side project for me, and has never been a source of any sort of income, so it is lower priority than family and work things.

I wish I had more free time these days, but sadly that is not in the cards.

**Comment by ofek** [comment]
@wbond Hello again man! Is there anything any of us can do to help get a new release out? I assume it's more than bumping/pushing a tag since it hasn't happened yet.

I totally understand time constraints, as I am dealing with that too, but considering the importance of this package (security-related and 8M downloads/month just on PyPI), it may be worth it to just cut a new release every month or 2 to ship fixes, etc. and let others maintain as much as possible.

Let us know how to help, please 🙏

**Comment by wbond** [comment]
Things are close for a new release. I've recently ripped out the EC math stuff and the optional libcrypto dependency.

I would like to get the following addressed before a new PyPi release:

 - https://github.com/wbond/asn1crypto/issues/124

The following two would be nice to have:

 - https://github.com/wbond/asn1crypto/issues/117
 - https://github.com/wbond/asn1crypto/issues/144

**Comment by ofek** [comment]
Awesome!

**Comment by wbond** [comment]
https://pypi.org/project/asn1crypto/ now has 1.0.0

**Comment by ofek** [comment]
@wbond Thanks dude, you rock!

**Comment by joernheissler** [comment]
🎉 Thanks!
