### ISSUE TITLE
Cannot load crypto.dll in _big_num_ctypes.py

### ISSUE THREAD

**Issue by amanb87** [wbond/asn1crypto#123]
I have been trying to work out imports in the asn1crypto package. While trying to do the `import _big_num_ctypes`  from asn1crypto\\_perf, I get the below error. I have crypto.dll installed in System32 & SysWOW64 folders and registered with regsrv32. This has been tested on Windows 7 64-bit with the Anaconda distribution of Python 3.6.7(32-bit) & Python 3.7(64-bit). Looking at the error, I realized there may be an architecture version conflict, so I tried on both 32-bit & 64-bit versions of Python but the error persisted. 

```
(py36_32) C:\Users\%USERPROFILE%>python
Python 3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 21:25:28) [MSC v.1915 32 bi
t (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from asn1crypto._perf import _big_num_ctypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\%USERPROFILE%\Anaconda3\envs\py36_32\lib\site-packages\asn1crypto\_
perf\_big_num_ctypes.py", line 39, in <module>
    libcrypto = CDLL(libcrypto_path)
  File "C:\Users\%USERPROFILE%\Anaconda3\envs\py36_32\lib\ctypes\__init__.py", line
348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```
However, the dll itself is successfully found:
```
>>> from ctypes.util import find_library
>>> testlib = find_library('crypto')
>>> testlib
'C:\\windows\\system32\\crypto.dll'
```
I also re-installed asn1crypto and its dependencies from `conda` but that didn't help either:
```
asn1crypto:   0.24.0-py36_0
cryptography: 2.4.1-py36h7a1dbc1_0
pyopenssl:    18.0.0-py36_0
```

**Comment by amanb87** [comment]
This is also open as a [question](https://stackoverflow.com/questions/49302516/where-to-get-and-install-crypto-dll-on-64-bit-windows).

**Comment by wbond** [comment]
The usage of libcrypto has been removed with 564e744e9b3ec01b542efcac57949a704e3de8a4, which will be part of the next release.
