### ISSUE TITLE
Error parsing X509

### ISSUE THREAD

**Issue by Sebubu** [wbond/asn1crypto#13]
Hey guys
I've found a problem parsing a certificate with oscrypto. It looks like it's a asn1crypto error.

Certificate: HTTPS certificate of https://www.admin.ch
```python
from oscrypto.asymmetric import load_certificate
cert = load_certificate('/home/severin/Downloads/admin.ch.crt')
cert.asn1.native
```
cert.asn1.native raises AttributeError: 'int' object has no attribute 'decode'
Stacktrace:

>  Traceback (most recent call last):
>   File "/home/osboxes/PycharmProjects/StrongMan/strongMan/tests/certificates/test_container.py", line 368, in test_load_cert
>     cert.asn1.native
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 2846, in native
>     self._native[name] = child.native
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 2846, in native
>     self._native[name] = child.native
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 3308, in native
>     self._native = [child.native for child in self]
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 3308, in <listcomp>
>     self._native = [child.native for child in self]
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 2846, in native
>     self._native[name] = child.native
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 1804, in native
>     self._native = self._parsed[0].native
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 3308, in native
>     self._native = [child.native for child in self]
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 3308, in <listcomp>
>     self._native = [child.native for child in self]
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 2846, in native
>     self._native[name] = child.native
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 829, in native
>     return self.chosen.native
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 3308, in native
>     self._native = [child.native for child in self]
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 3308, in <listcomp>
>     self._native = [child.native for child in self]
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 829, in native
>     return self.chosen.native
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/core.py", line 1128, in native
>     self._native = self.__unicode__()
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/x509.py", line 150, in __unicode__
>     return uri_to_iri(self.contents)
>   File "/usr/local/lib/python3.5/dist-packages/asn1crypto/_iri.py", line 135, in uri_to_iri
>     port = port.decode('ascii')
>  AttributeError: 'int' object has no attribute 'decode'

**Comment by wbond** [comment]
This should be fixed by 0ca5d03ac1b867ba07e54ee60c64bc6a8cf9f3eb. There will be a new release soon to include this fix.

**Comment by wbond** [comment]
Version 0.17.1 contains this fix.

**Comment by Sebubu** [comment]
Great! Thank you very much!
