### ISSUE TITLE
RFC 5755 Internet Attribute Certificate Profile for Authorization

### ISSUE THREAD

**Issue by ftbarata** [wbond/asn1crypto#131]
Hello, is it possible, using asn1crypto , to create an Internet Attribute Certificate Profile for Authorization?
According to RFC 5755, this kind of certificate don't carry public key.

I tried to use the TbsCertificate without subject_public_key_info, but I get:
```
 "ValueError: Field "subject_public_key_info" is missing from structure"
```

**Comment by joernheissler** [comment]
Are you looking for `cms.AttributeCertificateV2`?

**Comment by ftbarata** [comment]
Hi @joernheissler , I don't known this cms.AttributeCertificateV2 yet, but this name seems to be what I need, yes. Where can I find it?

**Comment by joernheissler** [comment]
https://github.com/wbond/asn1crypto/blob/master/asn1crypto/cms.py#L450

**Comment by ftbarata** [comment]
@joernheissler that's it! Are there examples or testing codes using AttributeCertificateV2 ?

**Comment by joernheissler** [comment]
Not aware of any, sorry.
Anyway, your issue appears to be solved, so closing this.
