### ISSUE TITLE
Travis CI is failing for PRs due to expired certs

### ISSUE THREAD

**Issue by space88man** [wbond/asn1crypto#139]
FYI

**Comment by dpward** [comment]
This is wbond/badtls.io#6.

@wbond Could this be fixed simply by running `scripts/generate.py` and `scripts/install.py` on the web server for https://badtls.io?

**Comment by wbond** [comment]
This has been fixed. The badtls.io hosting was moved from Ubuntu 12.04 to 18.04 and is on a standalone VM now with a ansible-scripted setup, which should make it easier to maintain in the future.

Sorry it took so long, but such is the way of open source projects sometimes.
