### ISSUE TITLE
Error parsing asn1crypto.x509.EmailAddress - tag should have been 22, but 12 was found

### ISSUE THREAD

**Issue by RomaLash** [wbond/asn1crypto#144]
Hello. 

My code:
`       raw_subject = raw_subject.native
`

When I tried to parse this cert 
`MIIDvjCCAqigAwIBAgIEVXFPzTALBgkqhkiG9w0BAQUwgaExCzAJBgNVBAYMAkRFMRMwEQYDVQQIDApUaHVlcmluZ2VuMQ8wDQYDVQQHDAZFcmZ1cnQxEjAQBgNVBAoMCUtleXdlYiBBRzEWMBQGA1UECwwNS2V5SGVscCBQYW5lbDEhMB8GA1UEAwwYa20zNDkyNy0wMS5rZXltYWNoaW5lLmRlMR0wGwYJKoZIhvcNAQkBDA5pbmZvQGtleXdlYi5kZTAiGA8yMDE1MDYwNTA3MjkxN1oYDzIwMjUwNjA1MDcyOTE3WjCBoTELMAkGA1UEBgwCREUxEzARBgNVBAgMClRodWVyaW5nZW4xDzANBgNVBAcMBkVyZnVydDESMBAGA1UECgwJS2V5d2ViIEFHMRYwFAYDVQQLDA1LZXlIZWxwIFBhbmVsMSEwHwYDVQQDDBhrbTM0OTI3LTAxLmtleW1hY2hpbmUuZGUxHTAbBgkqhkiG9w0BCQEMDmluZm9Aa2V5d2ViLmRlMIIBIDALBgkqhkiG9w0BAQEDggEPADCCAQoCggEBAK4HS2XPemRfn+wARSP885DfHn05+JDQe6KChNwMlKWwGMnwIwJh1ysyvgcNAYyB1uAB3DbAS0qkeVCGr7spQApD8DIk5GpuNmsrWm7s4/auwDiaUxxpj2tDGBGSNeaN36c+f1vKpED3SQdvTPLeKX0X3mx/yQbylQsfKrydgUr4nlfXa+QZHLHS+FvCDV+h1FzDb5Wdu4lLF0mdudo7rOBQsTVaccEfvCT79r1NocWL0/J6wpa4/Qs0cbxkTHCwgr9X7YpMBWtTmQl1wr/eN+yf9bx6xzCmRGJMD9Sjp2MUUTEfrQcLkB6aGWGgFYzHqUggX3kJPMHxw9pQq6Nz7ecCAwEAATALBgkqhkiG9w0BAQUDggEBAGE05k2ej7uKWTfkc6I0snDD/nqYlECCpkgAtZO0HKasihrICHewlyZt7hTMQVo77gZ3oeH5X1uJGGV5ITrrWDVHciYDGAeYSKWjYnZ2KtaC4UQN5+UBUkd59YDF+SYN34pqE+5N+UmfQDPOJX7C9v+sWiK9HouVKjNRNHAt0Ncz/Huwh5GOxMJfPaMFD5yJC4HYtj0uh5nTMppm+N/EKU3hXGtERXcRbRep8ovcwz1PpOkp+pnW9FJFjFfKRYdctzZ57g+GpQef2REUjasYJDXXObu9GDeanluZqINhd/7Qsoeygk5bcbsjOdpNJE/+aGCltJBWsWFfkSV1KM4Rg1E=`

I get that error: 

Error parsing asn1crypto.x509.EmailAddress - tag should have been 22, but 12 was found
    while parsing asn1crypto.x509.NameTypeAndValue
    while parsing asn1crypto.x509.RelativeDistinguishedName
    while parsing asn1crypto.x509.RDNSequence

Then I tried to parse this one at https://certlogik.com/decoder/
And all worked fine, unfortunately.

 What could it be?

**Comment by wbond** [comment]
So according to RFC 2986, email addresses have the OID `1.2.840.113549.1.9.1` and should use IA5String for the ASN.1 encoding - https://tools.ietf.org/html/rfc2985#page-26.

It seems whoever encoded this certificate is not following that RFC and is instead using UTF8String. We've got an existing workaround for parsing broken string encodings when some software uses PrintableString, so we'll likely have to add one for UTF8String also.

https://github.com/wbond/asn1crypto/blob/master/asn1crypto/x509.py#L188 is the current work-around, but I'm not sure off of the top of my head if `_bad_tag` can accept multiple values.

**Comment by wbond** [comment]
Here's an example of some software that was encoding improperly: https://bugs.openjdk.java.net/browse/JDK-4702543. Although it appears that bug was fixed long ago.

**Comment by wbond** [comment]
4a0b9718208e1e4619ee90e2f99237bb007ac480 adds a work-around for when encountering improperly encoded email address and DNS names.
