### ISSUE TITLE
asn1crypto raise exception parsing indefinite length

### ISSUE THREAD

**Issue by wfranzini** [wbond/asn1crypto#15]
Hi,

as showed in the test case addedd with #14 asn1crypto explodes parsing a .p7m file with indefinite lengths:

ValueError: Insufficient data - 57904015269414514108800405237541285051975119636830231669355043598084451101117 bytes requested but only 57362 available

**Comment by wbond** [comment]
This ended up being an issue with nested indefinite length values. It is fixed by 3534063c27b99f34a6049e8dc2743385d7921ee6. Thanks for the test case!
