### ISSUE TITLE
IntegerBitString encodes signed but decodes unsigned

### ISSUE THREAD

**Issue by joernheissler** [wbond/asn1crypto#151]
```python
from asn1crypto.core import IntegerBitString
data = IntegerBitString(-1234).dump()
print(data.hex(), hex(IntegerBitString.load(data).native))
```
Actual output: `030300fb2e 0xfb2e`
Expected: `-1234` or some Exception.
If the current behaviour is by intention, it should be documented.

Not sure if anyone uses this class.

`IntegerOctetString`, which sounds similar in purpose, cannot encode signed values.

**Comment by wbond** [comment]
Yeah, I believe this was something I was using during some early PDF work. I'll definitely make it clear that only positive values are supported and raise a value error if someone tries to encode a negative value in there.

**Comment by wbond** [comment]
In 3b330ff4d0fc59bacccc69972f3828286c18c97c I restricted IntegerBitString and IntegerOctetString to positive integers.
