### ISSUE TITLE
Is there a way to change the decoder used for x509.DirectoryString?

### ISSUE THREAD

**Issue by xulfir** [wbond/asn1crypto#155]
I've seen some x509 certs that seem to have UTF-8 data in a TeletexString x509.DirectoryString. e.g.
```python
original_data = b'\x14"ABCDEF pretend software co.\xef\xbc\x8cltd.'
ds = x509.DirectoryString.load(original_data)
ds.native
# Gives: 'ABCDEF pretend software co.ï¼Œltd.'
```
When they were probably expecting `\xef\xbc\x8c` to resolve to `，`, the UTF-8 fullwidth comma, e.g. `'ABCDEF pretend software co.，ltd.'`

Is there a way I can force the DirectoryString to use UTF8String to handle the data? I don't quite understand how/if I could alter the Choice without touching private data, so for now, my hacky attempt just replaces a byte in the header:
```python
x509.DirectoryString.load(b'\x0c' + original_data[1:]).native
# Gives: 'ABCDEF pretend software co.，ltd.'
```

Is there a better way? Thanks!

**Comment by wbond** [comment]
Currently there is a public API to use strict TeletexString value with X.509, but the fallback is Windows-1252.

I wonder if in a future version we should default to trying UTF-8 and if that fails use Windows-1252?

Here is how to you can work around the issue for now:

```py
from asn1crypto import x509

x509.NotReallyTeletexString._decoding_encoding = 'utf-8'
```

You'll want to do that before you try decoding anything.

**Comment by xulfir** [comment]
Nice. Thanks! I think that should work for me.
