### ISSUE TITLE
asn1crypto fails on macOS Catalina, due to loading unversioned /usr/lib/libcrypto.dylib

### ISSUE THREAD

**Issue by fxcoudert** [wbond/asn1crypto#158]
I know this sounds weird, but I'd filing an issue to document a problem in past versions of asn1crypto, even though it is now fixed in version 1.0.0 and later. Please feel free to close :)

On macOS 10.15 “Catalina”, we were seeing as part of Homebrew builds several python-related formulas fail to build, due to an abort in `pip`. The issue is the following:

- `pip` aborts, and the crash log contains this:
```
/usr/lib/libcrypto.dylib  
abort() called  
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.  
```

- That's because `/usr/lib/libcrypto.dylib` on Catalina is booby-trapped, and should not be used.
- It turns out is gets loaded from `asn1crypto/_perf/_big_num_ctypes.py`
- Because as part of `asn1crypto` there is no way to specific a specific library name or location for libcrypto.

Of course, when I finally managed to get the backtrace and find out the issue was located here, I then quickly discovered that this code was removed in https://github.com/wbond/asn1crypto/commit/564e744e9b3ec01b542efcac57949a704e3de8a4 and should no longer be a problem with asn1crypto 1.0.0 or asn1crypto 1.2.0.

**Comment by fxcoudert** [comment]
I can confirm that building ansible with asn1crypto 1.2.0 succeeds, while it failed with pre-1.0.0 versions.

**Comment by joernheissler** [comment]
Good to see that this change improved things for you :-)
See #100 and #113 for more details.
Or #157 for an example where code needs fixing now.

**Comment by dendisuhubdy** [comment]
Happened to occur this, so annoying!

**Comment by wbond** [comment]
If you are running into this it means you are running and old version of asn1crypto. The package no longer uses `libcrypto.dylib` on Mac.
