### ISSUE TITLE
x509.Certificate: Missing '_value' on '_subject_directory_attributes' field name

### ISSUE THREAD

**Issue by calillo** [wbond/asn1crypto#159]
Hi,

function 'def subject_directory_attributes_value(self)' of Certificate class return always 'None' value because _subject_directory_attributes never valued on 'def _set_extensions(self):'
I think '_subject_directory_attributes' have to be rename in '_subject_directory_attributes_value'

**Comment by joernheissler** [comment]
Hello,
got a (real) certificate which can be used as a test case?

**Comment by joernheissler** [comment]
@calillo can you please test the code?

**Comment by calillo** [comment]
yes, now works perfectly.
Thanks to all for this wonderful project!

**Comment by joernheissler** [comment]
you're welcome.

Reopening, because the issue isn't fixed until the fix is merged.

**Comment by wbond** [comment]
This was fixed as part of the 1.3.0 release
