### ISSUE TITLE
Cannot build with pybuild: command 'CleanCommand' has no such option 'all'

### ISSUE THREAD

**Issue by joernheissler** [wbond/asn1crypto#16]
$ pybuild
I: pybuild base:184: python3.5 setup.py clean
running clean
error: error in /home/wulf/git/oss/asn1crypto/.pybuild/pythonX.Y_3.5/.pydistutils.cfg: command 'CleanCommand' has no such option 'all'
E: pybuild pybuild:319: plugin distutils failed: exit code=1: python3.5 setup.py clean
 
$ cat .pybuild/pythonX.Y_3.5/.pydistutils.cfg
[clean]
all=1
[build]
build-lib=/home/wulf/git/oss/asn1crypto/.pybuild/pythonX.Y_3.5/build
[install]
install-layout=deb
install-scripts=/usr/bin
install-lib=/usr/lib/python3.5/dist-packages
[easy_install]
allow_hosts=None

I found a fix, but don't know how correct it is:
Add to setup.py:
boolean_options = ['all']
def initialize_options(self):
  self.all = None

More or less copy+pasted from /usr/lib/python3.5/distutils/command/clean.py

**Comment by wbond** [comment]
This should be fixed by 13df68b9a161e8d3d8615145d8b32aaeed1e947a
