### ISSUE TITLE
Support for brainpool ECC algorithms

### ISSUE THREAD

**Issue by johughes99** [wbond/asn1crypto#163]
Can support for brainpool ECC algorithms be added please.

**Comment by joernheissler** [comment]
Hello!
Got a link to the official specs and perhaps some example files?

**Comment by johughes99** [comment]
This is the main spec

https://tools.ietf.org/html/rfc5639

**Comment by joernheissler** [comment]
@johughes99 can you please test the code?

**Comment by johughes99** [comment]
I went to joernheissler/asn1crypto - and can't see any commits made today. Can you check?

**Comment by joernheissler** [comment]
The commits are in other branches.
Easier if you just click the links above (between you linking the rfc, and me asking you to test). Github automatically added links here when I pushed the code.

**Comment by johughes99** [comment]
Sorry i i thought you had done a complete release. Copied keys.py across and overwrote the one in /usr/lib/python3/dist-packages/asn1cyrpto. 

However, still got the same error

**Comment by joernheissler** [comment]
You should better create a virtualenv and install into it.

What error? Can you provide a testcase? It should be complete, but as small as possible, and show your problem.

**Comment by johughes99** [comment]
Im using VirtualBox which is my dev/test env

Attached is the relatively small python module. You will not be able to run it as - as its linking to our pkcs#11 lib. If you have problems using it with softhsmv2 I can try tomorrow and set that up
[convert.zip](https://github.com/wbond/asn1crypto/files/3801605/convert.zip)

**Comment by joernheissler** [comment]
How is that related to **asn1crypto** at all? I see that you opened https://github.com/eerimoq/asn1tools/issues/66 which appears to be an unrelated project.

**Comment by joernheissler** [comment]
> linking to our pkcs#11 lib

Out of interest, what kind of HSM are you using?

**Comment by johughes99** [comment]
Because under the hood python-pkcs11 uses asn1crypto to do some of its processing.  That's how I found that asn1crypto didn't support brainpool.

I'm testing a new HSM - which is not commercially available as yet.  It's a memory stick size device with support for various EC algorithms.

**Comment by joernheissler** [comment]
Okay; still an error message and proper test case would be helpful.
Best would be example files that you're trying to parse or generate.
And where did the asn1 spec you provided in the other ticket came from?

**Comment by johughes99** [comment]
Let me work on a test case for you.  I'm quite busy for the next few days - put let me see what I can do.

Attached is the zipped asn.1 snippet.
[EccP256CurvePoint.zip](https://github.com/wbond/asn1crypto/files/3803239/EccP256CurvePoint.zip)

**Comment by wbond** [comment]
The brainpool curves are part of the 1.3.0 release
