### ISSUE TITLE
cms.Name encoding error ?

### ISSUE THREAD

**Issue by pcece** [wbond/asn1crypto#177]
Dear all,

Many thanks for your valuable code.

I was doing some test to check if I've correctly understood CMS asn.1 syntax and X9.TR34 examples.

So I created the following examples :

```python
poiSignKeyInfo = cms.IssuerAndSerialNumber()

poiName = cms.Name().build(
    {
        "country_name": "BE",
        "organization_name": "nexo",
        "common_name": "Nimbus2001-SN00000851",
    }
)

poiSignKeyInfo["issuer"] = poiName
poiSignKeyInfo["serial_number"] = cms.Integer(
    60544976534679537650102612762681661070401724434
)
```

And tried to verify my encoding by parsing the result

```python
byteToVerify = hexlify(poiName.dump())
decodedByte = cms.Name()
decodedByte.load(byteToVerify)
print("Verification with ans1crypto : ", decodeByte)
```

which yields to the following error 
```
ValueError: Value [UNIVERSAL 19] did not match the class and tag of any of the a
lternatives in asn1crypto.x509.Name: [UNIVERSAL 16]
```

So I tried to check with pyasn1 in order to verify the encoding, and the result i what i expect :
Content of poiSignKeyInfo

```
IssuerAndSerialNumber:
 issuer=Name:
  rdnSequence=RDNSequence:
   RelativeDistinguishedName:
    AttributeTypeAndValue:
     type=2.5.4.6
     value=0x13024245
   RelativeDistinguishedName:
    AttributeTypeAndValue:
     type=2.5.4.10
     value=0x13046e65786f
   RelativeDistinguishedName:
    AttributeTypeAndValue:
     type=2.5.4.3
     value=0x13154e696d627573323030312d534e3030303030383531


 serialNumber=60544976534679537650102612762681661070401724434
```

So I'm wondering if there is an error in the encoding of cms.Name.

Should you need further details, please feel to ask.

Best regards.

**Comment by joernheissler** [comment]
Hello!
I added some formatting to your pastes. Hopes that's alright.

To load data into `asn1crypto` objects, you can't pass in a hex string.
This works for me: `decodedByte = cms.Name.load(poiName.dump())`

**Comment by pcece** [comment]
Hi Joern,

Many thanks for your prompt answer.
Formatting changes are OK, sorry I should have done it before.

Your solution is OK, many thanks.

Best regards.
