### ISSUE TITLE
ASN.1 syntax highlighting

### ISSUE THREAD

**Issue by pcece** [wbond/asn1crypto#178]
Dear all,

Thanks to your previous highlight, I was able to dive deeper in ASN.1 syntax and CMS structure.
Please forgive me in advance if I haven't read the Manual, but I was not able to find a method which could provide the structure of the element.

For instance, I was looking for something like 

`myElement = cms.ContentInfo() .......

myElement.decode()
`

Then this method may provide something like 

`
 SEQUENCE
 content_type : 
	 OBJECT IDENTIFIER
	 signed_data
 content : 
	 SEQUENCE
	 version : 
		 INTEGER
		 v1
	 digest_algorithms : 
		 SET
		 [ 0 ]
		 	 algorithm
				 sha256
		 	 parameters
	 encap_content_info : 
		 SEQUENCE
		 content_type : 
			 OBJECT IDENTIFIER
			 enveloped_data
		 content : 
			 SEQUENCE
			 version : 
				 INTEGER
				 v0
			 originator_info : 
			 recipient_infos : 
				 SET
				 [ 0 ]
				 	 version
						 v0
				 	 rid
						 issuer
							 country_name
								 BE
							 organization_name
								 nexo
							 common_name
								 Nimbus2001-SN00000851
						 serial_number
							 60544976534679537650102612762681661070401724434
				 	 key_encryption_algorithm
						 algorithm
							 rsaes_oaep
						 parameters
							 hash_algorithm
								 algorithm
									 sha256
								 parameters
							 mask_gen_algorithm
								 algorithm
									 mgf1
								 parameters
									 algorithm
										 sha256
									 parameters
							 p_source_algorithm
								 algorithm
									 p_specified
								 parameters
									 b''
				 	 encrypted_key
						 b'20139F59CC2A3400CA21287C1F63D3FE7CD8AAAF7EE17BEAE82560CABAF3E54C036513B4D1F2E9A0ADC756C52F6C8C52843F9BD67B0879C02B598A0F7EDEE8FB68C33146432946333AE843509E6FA33BA3C82A5D9F5FDB23E6182D0E5FD7ADAAD2C15F6510F7C48D498329C762C0000D906C1AF0D81715C4777C0C4C037424A2549E2A2F028BA40CAEBDECD388821EFC04C52D7EFCC71AFDBDBCFC438AD6CB4AA3FE73E420CF5FA3A290749D55F0EB851EB1AE060F3548D9DBD7EDDDCCCB63952E9D94DA7424C340ECAE78DF27AD4BDC4978A56766D0F5A59E63BDD7148ACB08E3694AC1D0A0E0FF0F87FE35578329A0BAB7AD470A0C056FCBFC1D40F3E3D2C3'
			 encrypted_content_info : 
				 SEQUENCE
				 content_type : 
					 OBJECT IDENTIFIER
					 data
				 content_encryption_algorithm : 
					 SEQUENCE
					 algorithm : 
						 OBJECT IDENTIFIER
						 tripledes_3key
					 parameters : 
							 b'A27BB46D1C306E09'
				 encrypted_content : 
						 b'FFD04017E9B208D56929877F531F702DEAF7402916217196F35B895C767F36F4486501625DF2518696B976695E28F0C9062F48E24C5394020E667990F390FBF93BAAA45A0521D7A9CA4C48A686CB5C8E94347D9D95A6FD1EBF0AA26B7F6115022BE2241CF135849A573CF08E19EA10AFEBAD6DB3B47F0CF32D5FEC1EB7285A0B8747C346A059638CB39E52EC5746BCBEC408842551D80F81'
			 unprotected_attrs : 
	 certificates : 
	 crls : 
	 signer_infos : 
		 SET
		 [ 0 ]
		 	 version
				 v1
		 	 sid
				 issuer
					 country_name
						 BE
					 organization_name
						 nexo
					 common_name
						 nexo-KeyInjectionServer-TM1
				 serial_number
					 53456422700275957421126573432849728692699229865
		 	 digest_algorithm
				 algorithm
					 sha256
				 parameters
		 	 signed_attrs
				 [ 0 ]
					 type
						 content_type
					 values
						 [ 0 ]
							 enveloped_data
				 [ 1 ]
					 type
						 1.2.840.113549.1.7.1
					 values
						 [ 0 ]
							 b'B0016K1TD00N0000'
				 [ 2 ]
					 type
						 1.2.840.113549.1.9.25.3
					 values
						 [ 0 ]
							 b'53675620D312085067D69431FAD6AC21'
				 [ 3 ]
					 type
						 message_digest
					 values
						 [ 0 ]
							 b'A48148D309E24D9E94E5E52045E18428B55BADBE200250467A49729C397A36D1'
		 	 signature_algorithm
				 algorithm
					 sha256_rsa
				 parameters
		 	 signature
				 b'64D0404B08A33B2E50A4088721D43349853B3B7FC951635E080B3F8D82E0E032A8D3AF5E65D5DD826F64E119EB43DB620867725AC9AC2AFED47BD7EEA52D24E990309CD3578DCEA40D1744B1B24B6C8D1CE252DAAD4BD72E1C1B66EDF5DA95501822B684D563F63CC020F6E39D1559337B7CACA157886933F75EB468A81C12A7BB7E2101781238A4E9124C3E80130D6C7BD7A61A289948A0356EE123E78F2BD94050B4D9DE5790CBBB37DDB7CB359F4693E1EA497E04613C5D16D1AFDE74E0E7F1259FFC0C2690D326F34B92BD3388D989A19531EC5D0302820FA74EEDA7CD7137ED8F2327D0279DA662ACAB82E6833F0C6A3AAE19782C9F996368E09B3AAA68'
		 	 unsigned_attrs
`

This method might help to find any misunderstanding or encoding error.

Many thanks in advance for your answer.

Best regards.

**Comment by wbond** [comment]
There are two options available:

`myElement.native` and `myElement.debug()`

The first one returns a native Python data type representation of the ASN.1 value. The second gives full encoding details of the object.

**Comment by pcece** [comment]
Many thanks for your prompt answer.

Well myElement.native doesn't really fit, since I was looking for something close to ASN.1 syntax used in RFC.
I will take a look at myElement.debug().

Many thanks for your great job.
Best regards.

**Comment by wbond** [comment]
You won't find anything like ASN.1 syntax output in asn1crypto.

If someone is interested in adding it, that sounds reasonable to me. Certain things won't be able to be represented since asn1crypto doesn't implement them. One example is max lengths.

**Comment by pcece** [comment]
Dear @wbond ,

Indeed i was looking at something close to the dump of dumpans1 (but was not aware of this tool).
So [https://github.com/wbond/asn1crypto/issues/186#](https://github.com/wbond/asn1crypto/issues/186#) hightlights this and how to use it.

So, everything is here with the pyasn1 module.

Many thanks and congratulations again, that's a great module.

Best regards.
