### ISSUE TITLE
Wrong structure for the Name object causes invalid CSR DER

### ISSUE THREAD

**Issue by williampiras** [wbond/asn1crypto#19]
Will,

I noticed this error debugging an issue with the CSR generator library, but it seems to be caused by an error int the way the Subject distinguishing name object is represented in the ASN.1 crypto element Name

In particular, page 114 of rfc5280 (https://tools.ietf.org/html/rfc5280) states that a Name hast the following structure.

    Name ::= CHOICE { -- only one possibility for now --
      rdnSequence  RDNSequence }

    RDNSequence ::= SEQUENCE OF RelativeDistinguishedName_

    DistinguishedName ::=   RDNSequence

    RelativeDistinguishedName ::= SET SIZE (1..MAX) OF AttributeTypeAndValue

    ....

    Attribute               ::= SEQUENCE {
          type             AttributeType,
          values    SET OF AttributeValue }
                -- at least one value is required

    AttributeType           ::= OBJECT IDENTIFIER

    AttributeValue          ::= ANY -- DEFINED BY AttributeType

    AttributeTypeAndValue   ::= SEQUENCE {
        type    AttributeType,
        value   AttributeValue }_

This implies that  in the generated CSR we should see something like

	SEQUENCE
		SET
			SEQUENCE
        		OID
				VALUE
		SET
	    	SEQUENCE
				OID
				VALUE

The subject domain name of the CSR generated by the last version available of CSR generator has the following structure:

	SEQUENCE
		SET
			SEQUENCE
				OID
        		VALUE
		    SEQUENCE
        		OID
		        VALUE

The issue that we see with this is that based on the field specified and base on the order they appear, the CSR is rejected or not. For instance the following CSR will be accepted because all the IDs are reported in the right order:

-----BEGIN CERTIFICATE REQUEST-----
MIIDGzCCAgUCAQAwgZoxgZcwCQYDVQQGEwJVUzARBgNVBAgMCkNhbGlmb3JuaWEw
FAYDVQQHDA1TYW4gRnJhbmNpc2MwMBcGA1UECgwQbXkgb3JnIDEyMzQ1Njc4OTAm
BgNVBAMMH215aG9zdDEyMzQ1Njc4OS5teWRvbWFpbjEyMy5jb20wIAYJKoZIhvcN
AQkBFhNhYmNAbXlkb21haW4xMjMuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEArzqYKehUC4uvhh/i4sN3Q8DqPoAG62ozz9KywKcyDQ6xxx/pbIpz
UVPlxFKPdI+7w+ytbSGyuHe0rqQEBAi2MNQdLISY+9MZ0grOu/cQH7vAXIM8JqZN
DJQSw49ohhuk3rg50rLbA0QpCiQMZ+3IQqPOE11oC0GEQtJQVF9z82sCBhzy3RF3
rw5Ro7KubJiSK+OlYZzqcEC6REUfu5SpTT7kDlMNP+519kktZW7fBFDmXBt+Uz69
flgUZVob/EpHQy/XbhWVJwrYRK6MOHxhhWG/+GyJHPWX5du6G0U5D0ddVFwbi8Qj
hcMkG7/dqD70o1U2GlorOSA/WexB5tVymQIDAQABoD0wOwYJKoZIhvcNAQkOMS4w
LDAqBgNVHREEIzAhgh9teWhvc3QxMjM0NTY3ODkubXlkb21haW4xMjMuY29tMAsG
CSqGSIb3DQEBCwOCAQEAmjMU1J1JINSVc4ClMeVXyUqIt8y9gesht+xMzUePCB9t
4Ax5zjDFGlYUO1z3lgLZaE9Ov46oiMXSU0D9h/HvZZJrxsEd4r8YYSMg/NMIxMVI
IHMeab97bhhIn3g9x2vdfnf3LVOig1N1nEWbLovKQ7f17obXX+bClph3wEuVaYWm
wJOkZyZXfHAawecqdK5LWzREUQNJ4AYpzkvWk77CpFsrFs+wO3puR8DyA2RDYGNG
YnRLAfhzIPHQg1x1lvXXW8lFfxD+eEa9q0SisqZp020BhAZ3hticDdspcUp3lpSa
8Ipuiiokjf7VxYTQMw5ZSOIZqWuTxZIWXs/AgCfbmA==
-----END CERTIFICATE REQUEST-----

The following CSR will be rejected

-----BEGIN CERTIFICATE REQUEST-----
MIIC9zCCAeECAQAwdzF1MAkGA1UEBhMCVVMwEQYDVQQIDApDYWxpZm9ybmlhMBQG
A1UEBwwNU2FuIEZyYW5jaXNjMDAXBgNVBAoMEG15IG9yZyAxMjM0NTY3ODkwJgYD
VQQDDB9teWhvc3QxMjM0NTY3ODkubXlkb21haW4xMjMuY29tMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1zz1e5+05DtmnXUOVUx7noYmEZ7dd9ja/zA+
YwDx3M0fU9m5UqDKTShUyX/jVCq17Eihv3goQZt4kYSsPRiHsitaA1LndQX5Bnd9
ZrbV3cTEU8qn4djas/V3vNSI8HZ2OOwff+6HHW8fTk04lkMOdWA+QQZAXZRYsix1
01vwmNTIuv9yX6L4QxV3dV5dvkgvgjVlQ1Mik348ycTJP6br1YgSdodEnS8KgzpB
2fm5eKfjmBKKMI8a49pzqSHLsfNY4i/5oUjHiwn3CIpCloUfiSkL10OFG0EfVnE8
Mx7vaz6jjgx5Chupzwy8AFsROHBvMLCBQRtherQ0pwvyHdTPYwIDAQABoD0wOwYJ
KoZIhvcNAQkOMS4wLDAqBgNVHREEIzAhgh9teWhvc3QxMjM0NTY3ODkubXlkb21h
aW4xMjMuY29tMAsGCSqGSIb3DQEBCwOCAQEAApSFaaOFd9meRqsbi7p/SLqp4ynF
me9YZPC/+VLyUMYArcpvCNJOkZNwupr66AXL+CXaLfRUOXSKBjWXtszHwuf2eQ83
Yfli8iD0Idxk6BVqZrekWPuXz7128wJ/sY6e842c0BfDhNgPLhXyaVLIkWHojh26
fwPxVt5tD6yVym6K+KAZQP4yroW7wHqnCyBAA5xnUAoL3ZKsyjwjbOn+4sEUxMqx
ZCciI63pG5jmvACXv49x58lBWrdEM6eUmDyFO/di92kmuAF8ro07uUYba5i2mqrs
Ph4UVmq+/aiF4QENEOEBw6fkZmFLqQbVOSrgMR1in0ustXCoHcO4uuDR6g==
-----END CERTIFICATE REQUEST-----

After a lot of digging in RFC/standards and some really helpful emails with the CA guys it looks like the issue here is that a CSR generated skipping the SET element for each RDNSequence produces a single SET that contains all the SEQUENCEs. When this happens the order the element and their content length matters in order to generate valid DER encoded content.

This happens because the rules to map ASN1 to DER state that a SET OF ASN1 element (PKCS uses SET OF instead of SET) has to contain a list of elements ordered by ascending value of tag (see end of section 5.15 http://luca.ntop.org/Teaching/Appunti/asn1.html). The DER encoding section also explain how to identify the discriminant tag when two elements tags are the same (30 HEX for the SET OF elements) and do the comparison (basically do the lexicographic comparison of the bytes that follow, so in this case the length field)

Looking at the asn1parse of the good CSR we see this 

    15:d=4  hl=2 l=   9 cons: SEQUENCE          
    17:d=5  hl=2 l=   3 prim: OBJECT            :countryName
    22:d=5  hl=2 l=   2 prim: PRINTABLESTRING   :US

    26:d=4  hl=2 l=  17 cons: SEQUENCE          
    28:d=5  hl=2 l=   3 prim: OBJECT            :stateOrProvinceName
    33:d=5  hl=2 l=  10 prim: UTF8STRING        :California

    45:d=4  hl=2 l=  20 cons: SEQUENCE          
    47:d=5  hl=2 l=   3 prim: OBJECT            :localityName
    52:d=5  hl=2 l=  13 prim: UTF8STRING        :San Francisc0

    67:d=4  hl=2 l=  23 cons: SEQUENCE          
    69:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
    74:d=5  hl=2 l=  16 prim: UTF8STRING        :my org 123456789

    92:d=4  hl=2 l=  38 cons: SEQUENCE          
    94:d=5  hl=2 l=   3 prim: OBJECT            :commonName
    99:d=5  hl=2 l=  31 prim: UTF8STRING        :myhost123456789.mydomain123.com

the tag sequence is 9 -> 17 -> 20 -> 23 -> 38. Everything works.

Looking at the asn1parse of the bad CSR we see this

    17:d=4  hl=2 l=   9 cons: SEQUENCE          
    19:d=5  hl=2 l=   3 prim: OBJECT            :countryName
    24:d=5  hl=2 l=   2 prim: PRINTABLESTRING   :US

    28:d=4  hl=2 l=  17 cons: SEQUENCE          
    30:d=5  hl=2 l=   3 prim: OBJECT            :stateOrProvinceName
    35:d=5  hl=2 l=  10 prim: UTF8STRING        :California

    47:d=4  hl=2 l=  20 cons: SEQUENCE          
    49:d=5  hl=2 l=   3 prim: OBJECT            :localityName
    54:d=5  hl=2 l=  13 prim: UTF8STRING        :San Francisc0

    69:d=4  hl=2 l=  23 cons: SEQUENCE          
    71:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
    76:d=5  hl=2 l=  16 prim: UTF8STRING        :my org 123456789

    94:d=4  hl=2 l=  38 cons: SEQUENCE          
    96:d=5  hl=2 l=   3 prim: OBJECT            :commonName
    101:d=5  hl=2 l=  31 prim: UTF8STRING        :myhost123456789.mydomain123.com

    134:d=4  hl=2 l=  32 cons: SEQUENCE          
    136:d=5  hl=2 l=   9 prim: OBJECT            :emailAddress
    147:d=5  hl=2 l=  19 prim: IA5STRING         :abc@mydomain123.com

the tag sequence is 9 -> 17 -> 20 -> 23 -> 38 -> 32. The CA rejects the CSR.

If the assumptions above are correct I see the two following issues:

1) The Name element should be modified so that each AttributeTypeAndValue is stored in its own SET OF

2) The DER encoding of the SET OF elements does not follow the mandatory tag sorting rule required by the DER encoding.

Thanks

**Comment by wbond** [comment]
Excellent, thanks for digging deep and finding these bugs!

**Comment by wbond** [comment]
Bug 2 was fixed by 3eeb96af94eaf528c1a947f300d014f243ed0b73.

Bug 1 was fixed by e1fa6cd5de4f533a1f15a0e20d643695b395325d.

Each has tests to verify the fixes. I'll probably do a new release soon, at which point I'll probably rev csrbuilder, certbuilder, etc to require the latest version of asn1crypto.

**Comment by williampiras** [comment]
That's awesome, thanks. I'll try to test the hash that you mentioned above with the CA. Do you already have an ETA for (I assume) 0.19.0?

**Comment by wbond** [comment]
I would use fc934bc357fcbd6dd6d2873727a3da9ef3ca924e for your testing.

I can release 0.18.1 as soon as you confirm the changes look good.

**Comment by williampiras** [comment]
The changes look good and now I'm able to generate CSRs that don't have the issues reported. Thank you for fixing the issues. Looking forward to get 0.18.1.
