### ISSUE TITLE
User defined x509 extension

### ISSUE THREAD

**Issue by ayushev** [wbond/asn1crypto#200]
Hello,

thanks for this library!
I'm using it for my project and now need to add a new x509 extension (non-standard) to create a CSR. Is there a way to add it from the user side?
I've added one line with oid in the ExtensionID class, and one line to the Extension class and my application works now, though only locally. I thought maybe there is a way to do it from the outside.

**Comment by joernheissler** [comment]
Hi,
should be easy to do:

```python
import asn1crypto.x509
asn1crypto.x509.ExtensionId._map["5.6.7.8"] = "foo"
asn1crypto.x509.Extension._oid_specs["foo"] = Foo
```

But perhaps asn1crypto could offer a function to do the same so users can call:
```python
Extension.register("foo", "5.6.7.8", Foo)
```

**Comment by ayushev** [comment]
Thank you, this is exactly what I was looking for!

**Comment by subhamagr** [comment]
@joernheissler Your solution doesn't work me. It is because of the internal `_reverse_map` attribute which gets generated by the `ans1crypto.core.ValueMap._setup` method. Following is what worked for me:

```python
import asn1crypto.x509
asn1crypto.x509.ExtensionId._map["5.6.7.8"] = "foo"
asn1crypto.x509.ExtensionId._reverse_map["foo"] = "5.6.7.8"
asn1crypto.x509.Extension._oid_specs["foo"] = Foo
```

Why is it that your solution doesn't work for me? What am I doing wrong?
