### ISSUE TITLE
cms how encrypt enveloped_data

### ISSUE THREAD

**Issue by zhongzunfa** [wbond/asn1crypto#206]
Hi, can you provider encrypt enveloped_data test case?

**Comment by zhongzunfa** [comment]
I find test_cms.py only provider parse.
please proivder encrypt enveloped_data case.

**Comment by zhongzunfa** [comment]
@wbond help

**Comment by joernheissler** [comment]
Hi there. You'd need some other library for the actual encryption, e.g. https://github.com/wbond/oscrypto or https://github.com/pyca/cryptography
asn1crypto can then be used to create the CMS structure.

It's usually easier to start from an existing file. Can you provide an openssl command that creates the type of file you'd like to have?

**Comment by zhongzunfa** [comment]
Thank you very much for your reply!

**Comment by zhongzunfa** [comment]
Thank you very much for your reply! @joernheissler

**Comment by wbond** [comment]
This seems to be a resolve question, so I am closing
