### ISSUE TITLE
How to verifiy a CSR

### ISSUE THREAD

**Issue by defacto64** [wbond/asn1crypto#216]
Hi, question: is it possible to verify a CSR (i.e. verify its signature) via asn1crypto? I have not been able to figure this out....

**Comment by joernheissler** [comment]
Hello. Asn1crypto is about ASN.1 and doesn't implement cryptographic algorithms like RSA or ED25519. You can extract the interesting parts of your CSR with asn1crypto and pass those values to another library which can verify it.
You'll need the public key, the cert request, signature algorithm and the signature.
If your goal is to verify a cert request, you might be better off using `cryptography.x509.CertificateSigningRequest` directly.
But if you love meddling around in ASN.1 structures, asn1crypto is what you want :-)

**Comment by defacto64** [comment]
OK, thank you.
