### ISSUE TITLE
Missing scrypt support

### ISSUE THREAD

**Issue by geitda** [wbond/asn1crypto#229]
Scrypt isn't recognized as a KDF algorithm. It can be used as an almost-drop-in-replacement for PBKDF2.
I submitted a PR https://github.com/wbond/asn1crypto/pull/226 two weeks ago that has gone apparently unnoticed.
Is it normal to have to specifically make a bug, even when the PR is already made?

**Comment by geitda** [comment]
Bump?? This issue has been open two weeks, and the PR for a month. At the absolute least can this get tagged as 'enhancement'?

**Comment by MatthiasValvekens** [comment]
Hey, as a fellow "outside contributor" to this project: maintainer bandwidth is not infinite, and sometimes PRs take time to get to. Hell, I've made PRs that took upwards of two months to merge. Please don't take offense to that, it's just the way FOSS works. Most maintainers are volunteers too, y'know. :)

If you _urgently_ need this addition, you can do either of the following two things:

 - Fork the library (the MIT license allows you to do that)
 - Register the ASN.1 structures you need from within your calling code (been there, done that; it's not nearly as bad as it sounds)

If neither of these suit your needs, then you'll just have to wait until someone with merge privs comes along. Simple as that.

**Comment by geitda** [comment]
Thanks for the insight. This bug is just an enhancement, so it's definitely low priority, but complete silence for a month was discouraging. A 15-second, "Thanks! We're pretty busy, but we'll look at this later," goes a long way for a FOSS newbie like myself.
I've done both of your suggestions - forked it so I could make the PR, and monkey-patched anywhere else I needed it. I wanted to try to be helpful / contribute back to this project as it's been very useful to me.

**Comment by geitda** [comment]
PR #226 merged.
