### ISSUE TITLE
Error parsing cms CompressedData

### ISSUE THREAD

**Issue by abhishek-ram** [wbond/asn1crypto#24]
I am working on implemented a file transfer protocol called AS2 and this requires messages to be compressed, signed and encrypted as per the CMS Specifications.

I have started with the compression and am able to parse the compressed data ASN1 generated using this package.

However I am getting the below error when I try to parse data generated from another tool that implements this protocol as well. 

```
Traceback (most recent call last):
  File "/Users/abhishekram/Documents/work/Research/pyAS2-lib/dev/tests/test_with_mecas2.py", line 16, in test_compressed_message
    in_mic_content = in_message.parse(infile.read())
  File "/Users/abhishekram/Documents/work/Research/pyAS2-lib/dev/pyas2lib/message.py", line 150, in parse
    decompress_message(mic_content)
  File "/Users/abhishekram/Documents/work/Research/pyAS2-lib/dev/pyas2lib/cms.py", line 31, in decompress_message
    return cms_content['content'].decompressed
  File "/Users/abhishekram/Documents/work/Research/pyAS2-lib/dev/venv/lib/python2.7/site-packages/asn1crypto/cms.py", line 883, in decompressed
    self._decompressed = zlib.decompress(self['encap_content_info']['content'].native)
  File "/Users/abhishekram/Documents/work/Research/pyAS2-lib/dev/venv/lib/python2.7/site-packages/asn1crypto/core.py", line 2770, in __getitem__
    raise e
ValueError: Error parsing asn1crypto.core.ParsableOctetString - method should have been primitive, but constructed was found
    while parsing asn1crypto.cms.EncapsulatedContentInfo
```

I am also attaching the [DER encoded compressed data](https://github.com/wbond/asn1crypto/files/526839/meca2_compressed.txt)

ASN1 for your reference.

**Comment by joernheissler** [comment]
I believe that your data is *not* properly DER encoded. That other tool (java?) is broken.
Instead of using one big primitive octet string with definite length, it uses a constructed / chunked one.

Or did I miss something in the standards which allow you to use this encoding?

What I'm wondering about: Can't asn1crypto parse any BER-encoded data? Because it might be valid BER, just not valid DER.

**Comment by wbond** [comment]
I believe it should be able to handle indefinite length structures. Unfortunately I haven’t had time to look at this yet. Just got my main computer back from being repaired, so I’m a little back-logged.

**Comment by wbond** [comment]
So yes, asn1crypto *does* handle parsing indefinite length structures, however it doesn't currently support that when parsing fields in a structure.

I'm torn about allowing parsing BER inside of what may be a DER structure. Mostly because the code that checks that tends to help detect other errors in encodings.

Perhaps I should have it ensure data is either primitive definitive or constructed with indefinitely length for non-sequence types.

**Comment by wbond** [comment]
Alright, as of d08dae573ea92f915cd3f43200a20da305bc9fde, it will now allow a BER-encoded indefinitely-length value inside of another data structure. It only allows the method to be a mismatch for a value if it is an indefinite-length encoding.

**Comment by abhishek-ram** [comment]
@wbond Thank you for the fix. I am now able to parse the compressed content, however when I try to decompress the message I get the following error:

`error: Error -3 while decompressing data: incorrect header check`

**Comment by wbond** [comment]
Could you like to the code that is being used to generate the ASN.1 structures?

Also, could you show what Python code is being used to decompress the content?

**Comment by abhishek-ram** [comment]
I do not have access to the code that is generating this ASN.1, however when I am extracting the compressed content from the binary file using the `dd` command I am able to decompress successfully using `zlib`

Here is the code I am using to decompress the file

```python
from asn1crypto import cms
fp = open('mecas2_compressed.raw', 'rb')
cms_content = cms.ContentInfo.load(fp.read())
cms_content['content'].decompressed
```

**Comment by wbond** [comment]
I don't think there is anything wrong with asn1crypto here, but rather with the code that is generating the ASN.1. Here is code that gets the content you want. However, based on this code, it seems there are a number of issues with the ASN.1:

 - It should be encoded in DER, not BER (the original issue, where indefinite length encoding was used)
 - The CMS data is encoded as CompressedData, but the encapsulated content is no ZLIB compressed like the OID says it is
 - Instead, the encapsulated content is a concatenation of 10 OctetString values
 - If the 10 OctetString values are concatenated together, the results can be decompressed via zlib

```python
from asn1crypto import cms
import zlib

fp = open('mecas2_compressed.raw', 'rb')
cms_content = cms.ContentInfo.load(fp.read())
cms_content['content'].decompressed

encap_data = cms_content['content']['encap_content_info']['content'].native
read = 0
data = b''
while read < len(encap_data):
    value, read = core._parse_build(encap_data, read)
    data += value.native
print(zlib.decompress(data))
```

**Comment by wbond** [comment]
So apparently the issue with was with my understanding of how BER encoding handles indefinite length encoding. Version 0.22.0 properly fixes this for all different types of octet strings and textual strings.

**Comment by abhishek-ram** [comment]
Yes this works perfectly now, thanks !!!!
