### ISSUE TITLE
How to parse certificate_policies_value

### ISSUE THREAD

**Issue by dwabisch** [wbond/asn1crypto#250]
Hi together, 

I am trying to get the OID from my certPolicy. 
I load a cert and got the policy like this:

certPolicy = cert.certificate_policies_value

When I print it out I get this one: 
<asn1crypto.x509.CertificatePolicies 140403662836112 b'0C0A\x06\x0b+\x06\x01\x04\x01\x81\x9d{\x04\x01\x010200\x06\x08+\x06\x01\x05\x05\x07\x02\x01\x16$https://www.test.com'>

But how can I get only the OID out of the variable (certPolicy) ?

**Comment by MatthiasValvekens** [comment]
Assuming there's only one policy (warning: untested): `cert.certificate_policies_value[0]['policy_identifier'].dotted`.

**Comment by dwabisch** [comment]
Thanks for the fast reply! 

I tried it like this before and got always the error: 

cert.certificate_policies_value[0]['policy_identifier'].dotted

TypeError: 'NoneType' object is not subscriptable

**Comment by MatthiasValvekens** [comment]
That's what you would get if the cert doesn't have the cert policies extension at all. Are you sure that this is the same certificate object as the one in your original post? If so, try these in order to see which one fails:

```python
cert.certificate_policies_value[0]
cert.certificate_policies_value[0]['policy_identifier']
cert.certificate_policies_value[0]['policy_identifier'].dotted
```

**Comment by dwabisch** [comment]
Thank you very much!
This was the problem. 
My first example does not have any cert policies. 
I just tried it with an other cert, now it works.
