### ISSUE TITLE
Issue report: x509.Name fails to process the TCG OIDs (2.23.133.2.*)

### ISSUE THREAD

**Issue by joseph-lo-nvtw** [wbond/asn1crypto#260]
Hi,

I meet an issue when creating the properties of TCG OIDs by using x509.Name.

The sample code:
x509.Name.build(
  {
    "tpm_manufacturer" : "some str",
    "tpm_model" : "some str",
    "tpm_version" : "some str",
  }
)

The error log:
x509.Name.build(
 ^^^^^^^^^^^^
  File "asn1crypto/x509.py", line 1034, in build
    NameTypeAndValue({
  File "asn1crypto/core.py", line 3430, in __init__
    raise e
  File "asn1crypto/core.py", line 3414, in __init__
    self.__setitem__(key, value[key])
  File "asn1crypto/core.py", line 3570, in __setitem__
    new_value = self._make_value(field_name, field_spec, value_spec, field_params, value)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asn1crypto/core.py", line 3817, in _make_value
    raise TypeError(unwrap(
TypeError: value value must be asn1crypto.core.UTF8String, not asn1crypto.x509.DirectoryString
    while constructing asn1crypto.x509.NameTypeAndValue

After fixing the "_oid_specs" in "class NameTypeAndValue", it works for me.
        'tpm_manufacturer': DirectoryString,
        'tpm_model': DirectoryString,
        'tpm_version': DirectoryString,
        'platform_manufacturer': DirectoryString,
        'platform_model': DirectoryString,
        'platform_version': DirectoryString,

The original type was "UTF8String".

Thanks.

**Comment by jinhua115** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by joernheissler** [comment]
Hi,
I think (really not sure!) the problem is here:
https://github.com/wbond/asn1crypto/blob/master/asn1crypto/x509.py#L1028-L1031
```python
  else:
     value = DirectoryString(
                    name=encoding_name,
                    value=encoding_class(attribute_value)
                )
```

The build function assumes, with some exceptions, assumes that everything is a DirectoryString. When this code is changed to use the type from `NameTypeAndValue._oid_specs` it works as expected.

**Comment by joseph-lo-nvtw** [comment]
Hi,

Regarding the document of TCG EK Credential Profile below.
https://trustedcomputinggroup.org/wp-content/uploads/TCG-EK-Credential-Profile-V-2.5-R2_published.pdf

In section 3.2, there is a table mentioned the type of subject alt name for TPM Manufacturer, model, and version should be GeneralName and directoryName.

Does that mean we should fix this as the comment 1 mentioned?

Thanks.

**Comment by jinhua115** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by wbond** [comment]
Yes, it looks like switching it to use the data from `NameTypeAndValue._oid_specs` is probably the correct move.

**Comment by wbond** [comment]
@joseph-lo-nvtw I looked at https://trustedcomputinggroup.org/wp-content/uploads/TCG-EK-Credential-Profile-V-2.5-R2_published.pdf and it still specifies UTF8String for `tcg-at-tpmManufacturer` (e.g. `2.23.133.2.1`), etc.

**Comment by joseph-lo-nvtw** [comment]
Yes, the final raw binary string in ASN1 is UTF8String.

But regarding Table 1 in section 3.2, the RFC5280 type of Subject Alternative Name is directoryName.
Which data type should we use here?
https://github.com/wbond/asn1crypto/blob/master/asn1crypto/x509.py#L689

With UTF8String, it doesn't work correctly. The x509.Name.build logic doesn't accept UTF8String data type.

Thanks for your reply.

**Comment by wbond** [comment]
The code at #270 should fix this

**Comment by joseph-lo-nvtw** [comment]
Hi @wbond ,

Thanks for the fix. I have verified it.
