### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by whitslack** [wbond/asn1crypto#267]
Does asn1crypto support Python 3.12? If so, then please add 3.12 to the [list of supported Python versions](https://github.com/wbond/asn1crypto/blob/master/readme.md#dependencies) in the README.

**Impetus:** The [`dev-python/asn1crypto`](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/asn1crypto/) Gentoo package currently is not declaring support for Python 3.12, but I maintain a dependent package whose only remaining hangup to 3.12 is asn1crypto.

**Comment by wbond** [comment]
I've added the appropriate metadata, so the next release will be marked as such
