### ISSUE TITLE
Specify default encoding for TeletexString

### ISSUE THREAD

**Issue by athoms** [wbond/asn1crypto#27]
I need to work with some certificates created by OpenSSL which used TeletexString with Latin-1 encoding for the commonName of the subject:
````
asn1crypto.x509.NameTypeAndValue Object #48061904
  Header: 0x300d
    constructed universal tag 16
  Data: 0x060355040314064dfc6c6c6572
    Field "type"
      asn1crypto.x509.NameType Object #48061968
        Header: 0x0603
          primitive universal tag 6
        Data: 0x550403
          Native: common_name
    Field "value"
      asn1crypto.x509.DirectoryString Object #48061744
        Data: 0x14064dfc6c6c6572
          asn1crypto.core.TeletexString Object #48062096
            Header: 0x1406
              primitive universal tag 20
            Data: 0x4dfc6c6c6572
              Native: Mþller
````

The value "Mþller" should be "Müller".  If I change the default encoding via `asn1crypto.core.TeletexString._encoding = 'latin1'` then the value is correctly decoded. But that feels very dirty. :wink:
Is there an official way to change the default encoding? I couldn't find one.

**Comment by wbond** [comment]
Hmm, interesting. `value.contents.decode('latin1')` may work, but that requires you deal with each individual value.

I suppose there isn't really a reason we can't create a class method to allow overriding the encoding for any `AbstractString` class.

**Comment by athoms** [comment]
I tried decoding the values separately, but
```subject.chosen[0][0]['value'].chosen.contents.decode('latin1')```
seems like a debugging nightmare compared to ```subject.native['common_name']```.

I'm curious why you want to use a class method to allow overriding the encoding. Do you want to check if the specified encoding is a valid value?

**Comment by wbond** [comment]
I'm just thinking of adding a class method since the `_encoding` value is set per-class in `core.py`, and `_` generally indicates something is private. I suppose we could just change it to `encoding` so it is public.

For the most part I do like to check data types to prevent accidental errors, but that shouldn't really be that important here.

**Comment by wbond** [comment]
As of 1ba880ef26e37151e71b9968ba1d29b2573cfd43, we now use cp1252 (Windows-1252), which is a superset of latin1 (ISO-8859-1), when decoding certificates. This should allow for compatibility with reading OpenSSL certs.
