### ISSUE TITLE
CMS Example

### ISSUE THREAD

**Issue by saferoom-app** [wbond/asn1crypto#46]
Hi, 

Can you provide one example how to generate CMS structure with 2 PFX files. I am trying to understand the code and I can't get the idea how to generate CMS

Thanks in advance

**Comment by wbond** [comment]
Unfortunately I likely won't have time to write up an example any time soon. However, PFX (PKCS12) is a somewhat complex structure.

There is code in oscrypto that decodes/reads pkcs12 files: https://github.com/wbond/oscrypto/blob/master/oscrypto/keys.py#L431-L691. You could reverse engineer that to create a PKCS12 file.

Understanding the structure of a PKCS12 file and the algorithms, options for encryption, etc is probably a good idea if you are planning on implementing this. At least a read or two over https://tools.ietf.org/html/rfc7292 would be good.

**Comment by joernheissler** [comment]
@saferoom-app , do you have such a CMS file? Then I'll try to give you the code to recreate it.

**Comment by saferoom-app** [comment]
Hi, @joernheissler 
In the attach you can find the example CMS file, generated by "openssl cms" utility. This ZIP contains the following:

- 3 key pairs (private keys are password-protected)

- Passwords file (passwords for all private keys)

- Command file

- Original data file (data.txt) and encrypted CMS (that is I believe is called EncryptedData structure)

So, I can decrypt this structure, but I want to get a list of certificates within this CMS and manage them somehow

Thanks a lot for your help
[cms.zip](https://github.com/wbond/asn1crypto/files/960974/cms.zip)

**Comment by joernheissler** [comment]
#!/usr/bin/env python3

    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
    from cryptography.hazmat.primitives import padding

    from asn1crypto import pem, cms, x509

    import gmpy2
    import base64

    data = 'some data only for Alexey Zelenkin and Andrey Zelenkin\r\n'
    data = data.encode('UTF-8')

    iv = bytes.fromhex('45403D8FE45BB82CB5E9357513F8B836')
    key = bytes.fromhex('186eafb6df43973571c608017aacdb628cf82f2aa160a90c3d6eceb9ffa9df26')

    recipients = [
        ('zelenkin',  bytes.fromhex(
            '5375177617426767204ec96746df32fdfd3b1984311a4c851c7dd319311d6bd5aa671e03bf18c9c9c3b22de47579c36e'
            '2cd59e1f9e77be4b8e556c019869c2cd2730f34f82dd51a6c596cec917d472ed1e8b174757a81b3fd7a4cb41d162405e'
            '3da461c315a611f4d8f1d46d8aeb0c25f6e1c3ec51f2908396b7b1afcf488841324e7241f05d711bda4a7f9692a3f718'
            '7b75d091e16293179742ca6e2548e9f2ba685afa6a0fa04c387c756ade794becef16d83595abb9453d463206cd95d276'
            '8766826cfc2e0d321c437ca80b86c1010c40515702e37daf5921f76013'
        )),
        ('azelenkin', bytes.fromhex(
            '288b590b05d862e56d60ae44cdb3fccdc118d9bc68eba32b4afcd62c44ae316443369f0f180a47d6fbb82d5b0cb733a2'
            'dbfdb2e1e7da59e62aa3e8768054f5cc48e5bae5b16c3205275bf847d9700e794d066e10cea108c320d1db3b0dcd5dd5'
            '92b4f1c8096ec80ed9a007c1d6aa058784e0a0e31d9c295050b898bb0f61814e1c2130713207a6dc769b40722bee9f9b'
            'fe94f7c70584c9d6abc69f8911c4b02a03da86d86f07e7462b9843e6401df5f97de84e2b394046efc842fba515bcbbb9'
            'e9fc7336d691777297b32b7bf30680597e62f36e2ef9803f2476f6e29d'
        )),
        ('izelenkin', bytes.fromhex(
            '04ae37f862d140756d374c871e91c7091de9ce0e0628b25d2c9203bfc24ed724c482f952be43dad36d5eb0d6e7b4518e'
            '0d65d4ad838fcbfa8c9769727c2196acbe0bc2b42ee82f724b5dadbd16aa6939127680cb6b0450a6c1316e5b935a62e6'
            '3bed3b4999dc59a45d304d73fcab87664b6ed3e5280377fdd5c6c2dff75e21bcd56cd340a47bf084f708cbbeb62eb3a5'
            'f8b937e32080f50dc19760231e0cb5b67fbe1d14643ada9c36228638b11b04bec38340b344edbf97b40d5dad616725e0'
            '98f06d6d663816303d20a9bb16fb71ec5105d76fe4294c5c669d40ae8f'
        )),
    ]

    backend = default_backend()

    padder = padding.PKCS7(128).padder()
    padded_data = padder.update(data) + padder.finalize()

    cipher = Cipher(algorithms.AES(key), modes.CBC(iv), backend=backend)
    encryptor = cipher.encryptor()
    encrypted_data = encryptor.update(padded_data) + encryptor.finalize()

    recipient_infos = []
    for recipient, pad_bytes in recipients:
        with open('{}.public.pem'.format(recipient), 'rb') as fp:
            cert = x509.Certificate.load(pem.unarmor(fp.read())[2])

            # openssl and pyca/cryptography can't specify the exact padding, so encrypt manually.
            # Don't do this as home, kids!
            # Usually you should use https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#encryption
            plain = b'\x00\x02' + pad_bytes + b'\x00' + key
            pub = cert.public_key.unwrap()
            encrypted_key = gmpy2.powmod(
                int.from_bytes(plain, 'big'),
                pub['public_exponent'].native,
                pub['modulus'].native)
            encrypted_key = int(encrypted_key).to_bytes(
                (pub['modulus'].native.bit_length() + 7) // 8,
                'big')

        recipient_infos.append(cms.KeyTransRecipientInfo({
            'version': 'v0',
            'rid': cms.IssuerAndSerialNumber({
                'issuer': cert.issuer,
                'serial_number': cert.serial_number,
            }),
            'key_encryption_algorithm': {
                'algorithm': 'rsa',
            },
            'encrypted_key': encrypted_key,
        }))

    ci = cms.ContentInfo({
        'content_type': 'enveloped_data',
        'content': {
            'version': 'v0',
            'recipient_infos': recipient_infos,
            'encrypted_content_info': {
                'content_type': 'data',
                'content_encryption_algorithm': {
                    'algorithm': 'aes256_cbc',
                    'parameters': iv,
                },
                'encrypted_content': encrypted_data,
            },
        },
    })

    cms_bytes = ci.dump()
    cms_b64 = base64.b64encode(cms_bytes).decode()

    print('MIME-Version: 1.0')
    print('Content-Disposition: attachment; filename="smime.p7m"')
    print('Content-Type: application/pkcs7-mime; smime-type=enveloped-data; name="smime.p7m"')
    print('Content-Transfer-Encoding: base64')
    print('')
    while cms_b64:
        print(cms_b64[0:64])
        cms_b64 = cms_b64[64:]
    print('')

**Comment by saferoom-app** [comment]
@joernheissler 

Thanks a lot for the example. One more question: how can i parse this CMS structure: get the content and the list of recipients. For example, I've received the CMS from other source and I want to get the list of certificates (recipients)

Thanks

**Comment by joernheissler** [comment]
from asn1crypto import cms
    ci = cms.ContentInfo.load(der)
    for rec in ci['content']['recipient_infos']:
        rid = rec.chosen['rid'].chosen
        print(rid['issuer'].native)
        print(rid['serial_number'].native)

Where "der" is the base64 decoded version of your cms file, i.e. bytes type.
