### ISSUE TITLE
SCEP support?

### ISSUE THREAD

**Issue by laurivosandi** [wbond/asn1crypto#52]
Hello, first of all thanks for usable Python modules. It made it reasonably simple to implement SCEP stuff in few evenings. Feel free to copy-paste and generalize, this should make your life significanlty easier:

https://github.com/laurivosandi/certidude/commit/5ae872e1ea2916bd90e0655afa8847383553a03a

I'll be uploading SCEP client side code in next days. The server side seems to be usable with SSCEP at least.

**Comment by wbond** [comment]
I am not familiar with SCEP, but if you want to submit a PR with supporting links to RFCs, I'd be happy to review and include it.

**Comment by laurivosandi** [comment]
Alrighty, I can give a try. What about those CMSAttributeType mappings which haven't been described in cms.py? Should I add them there or do you have some other elegant way to do it?

**Comment by wbond** [comment]
I'm not quite sure what you are referring to. Could you link to it so I can try and understand?

**Comment by laurivosandi** [comment]
Hi, it's right there https://github.com/laurivosandi/certidude/commit/5ae872e1ea2916bd90e0655afa8847383553a03a#diff-10a20cbd25ebcd233adfded18109724dR14

**Comment by wbond** [comment]
That's the current way I have to implement such features. If you think there is a better way, I'd be open to discussing it.

**Comment by laurivosandi** [comment]
I am saying monkey patching on my end doesn't look right, should I do a PR for cms.py modifications in asn1crypto or is there another way?

**Comment by wbond** [comment]
Oh, yes, what I was asking for was a PR where you add these structures to asn1crypto. I presume that cms.py would be the correct location. I don't know anything about SCEP, but I will check it out when I have time to review.

**Comment by wbond** [comment]
Closing since it's been four years, and I don't foresee learning this and adding it myself.
