### ISSUE TITLE
Modify CMS structure

### ISSUE THREAD

**Issue by saferoom-app** [wbond/asn1crypto#55]
Hi,
Is it possible to take existing CMS structure with 3 recipients, remove one of the recipients and have a new CMS structure with 2 recipients?

BR,
Alexey

**Comment by joernheissler** [comment]
I don't see why not.
You'll probably need to build a second structure based on original one.
#46 might help.

I'm beginning to think that the documentation needs CMS examples.

**Comment by wbond** [comment]
I'd definitely be down with some CMS examples, but I haven't dealt with it too much, so I wouldn't be too keen on writing it myself. I obviously know the syntax and what is available, but not the common ways in which CMS is used.

So far I've dealt with parsing PKCS#12 and some PDF-related CMS, but that is it.

**Comment by saferoom-app** [comment]
@joernheissler 
Thanks for response. Issue closed
