### ISSUE TITLE
Create a asn1crypto-testdata pypi package + automate release

### ISSUE THREAD

**Issue by cooperlees** [wbond/asn1crypto#59]
Trying to run the unittests in my environment I could not get them to work:

```bash
[cooper:~/asn1crypto-0.22.0:]$ ~/virtualenvs/setup_py_fun/bin/python3 setup.py test
running test
running egg_info
writing asn1crypto.egg-info/PKG-INFO
writing dependency_links to asn1crypto.egg-info/dependency_links.txt
writing top-level names to asn1crypto.egg-info/top_level.txt
reading manifest file 'asn1crypto.egg-info/SOURCES.txt'
writing manifest file 'asn1crypto.egg-info/SOURCES.txt'
running build_ext
tests (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'tests'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

Playing with setup.py now.

**Comment by wbond** [comment]
Did you extract from the tarball on pypi, or checkout from git?

**Comment by cooperlees** [comment]
0.22.0 on pypi - I didn't see a commit talking about anything fixing `python setup.py test`
- Did I miss it?

**Comment by wbond** [comment]
I don't include tests on the pypi releases since users don't needs all of the test fixtures, etc.

**Comment by cooperlees** [comment]
Ahhh - Well I have a use case for you:
- I pip download with --no-binary :all:
- Extract
- try run unit tests in my env to make sure we're not causing any pain to ourselves. I also encourage other people to do this!

Can we in future releases push the tests? I now need this module as Cryptography now needs this package.

I apologize not running ls before jumping into setup.py ... #noob

**Comment by wbond** [comment]
You can use the 0.22.0 tag from git. I don't really like the idea of adding 3MB of test data to every install of cryptography in the wild.

**Comment by cooperlees** [comment]
Ok, maybe a separate test package like cryptography-vectors then maybe?

**Comment by wbond** [comment]
I'd be open to a PR that allows me to run `run.py release` and create such a package and publish it to pypi. I imagine there would need to be some edits to `dev/release.py` to handle creating the sdist, but I'm not sure what other changes would need to be made in terms of the `fixtures_dir` in each of the `tests/test_*.py` files.

I don't personally have a use case for it, so it would be at the bottom of the priority list when I get time for open source.

**Comment by cooperlees** [comment]
Nice. Lets see if either of us gets time. Then we could make this main package have a tests_dep on the new package. This would allow have automatic unit test runs when we change our OS's / libraries etc. etc.

**Comment by coreycb** [comment]
Hi, I'm working on getting the asn1crypto package supported in main for Ubuntu, however it'll be tough to get in to main without having tests to run. Most python projects that I've dealt with include tests, and I think it's a worth the effort. It's very useful for downstream distros, etc to ensure they've not regressed anything.

**Comment by wbond** [comment]
I looked into this a little. It seems:

 1. The tests dir would need to become a new package `asn1crypto-tests`
 2. The `setup.py` would need to use that for `test_suite`
 3. `dev/tests.py` would need to be updated to import from `asn1crypto-tests` also

It seems that the cryptography package has a subdir for the vectors and a separate `setup.py` there. The complicated thing seems to be handling a local copy of `asn1crypto-tests` versus importing an installed version. Just glancing through the cryptography `setup.py`, it seemed there were some gymnastics to handle that.

**Comment by wbond** [comment]
Recent work in master has gotten ready for a separate tests package that will be published on PyPi. I'll update this once it is pushed up with the next release.

**Comment by wbond** [comment]
https://pypi.org/project/asn1crypto-tests/ is now available
