### ISSUE TITLE
Handle TeletexString as iso-8859-1

### ISSUE THREAD

**Issue by EnTeQuAk** [wbond/asn1crypto#60]
So I came across a pkcs7 signature that has a x509 `common_name` that includes a `{` and was generated my m2crypto and asn1crypto chokes on it.

M2Crypto simply forwards asn1 encoding to openssl and I found https://wiki.openssl.org/index.php/Manual:Req(1)#BUGS which states that OpenSSL encodes TeletexString as ISO-8859-1 (Latin 1). Then I found https://github.com/etingof/pyasn1/blob/master/pyasn1/type/char.py#L241-L250 which kinda verifies that and wondered if we could implement a fallback in asn1crypto that falls back to latin-1 if we run into a decoding problem? Or, maybe even kick out T61 and just use latin-1?

See https://github.com/mozilla/signing-clients/pull/24 the signature in question and a traceback.

**Comment by wbond** [comment]
Related is #27.

The issue, in general, it kinda of hard to make a decision about.

It seems for web certificate usage, we need `core.TeletexString` to be latin-1, but for other usage it should be the real ITU T.61 encoding.

Perhaps we default latin-1 and provide a method to force T.61? If so, should the "strict" mode be a `contextmanager`, or a global library function?

**Comment by wbond** [comment]
After reflecting on this some more, I think the correct approach is going to be to create an extension of `core.TeletexString` that uses `latin1` and use that within `x509.Certificate`. That way non-x509 usage of asn1crypto doesn't need to work around the compatibility shim.

I'll try to get this into the next release I do.

**Comment by EnTeQuAk** [comment]
Sorry for the late reply, I think that sounds like a great idea. As far as I can see x509 certificates are mostly affected by this so let's maybe give it a try!

I can help on this, if you need anything just le tme know!

**Comment by wbond** [comment]
As of 1ba880ef26e37151e71b9968ba1d29b2573cfd43, we now use cp1252 (Windows-1252), which is a superset of latin1 (ISO-8859-1), when decoding certificates. This should allow for compatibility with reading OpenSSL certs.

**Comment by EnTeQuAk** [comment]
Awesome, thanks a lot for the quick turnaround! Looks great.
