### ISSUE TITLE
LDAP or HTTPS can be used for OCSP

### ISSUE THREAD

**Issue by Doowon** [wbond/asn1crypto#66]
It is a rare case but LDAP and HTTPS are used for OCSP. In the code, only http is considered to be used for OCSP.

Here is one of the examples.

```
Authority Information Access:
                OCSP - URI:http://pki.aloaha.com/CertEnroll/pki.aloaha.com_aloaha.crt
                OCSP - URI:ldap://pki.aloaha.com/CN=aloaha,CN=AIA,CN=Public%20Key%20Services,CN=Services,CN=Configuration,DC=aloaha,DC=com?cACertificate?base?objectClass=certificationAuthority
```

Another example for https

`https://ocsp.verisign.com`

https://github.com/wbond/asn1crypto/blob/2068a8abfd5e34210f5dc521cbdec672c87c95bd/asn1crypto/x509.py#L2380

**Comment by wbond** [comment]
This should be addressed by 10f6d190d518224775bdb34b61afa1b95b2c33cc
