### ISSUE TITLE
cryptography import asn1crypto(asn1crypto>=0.21.0)，but asn1crypto has a bug fixed and has not new release 

### ISSUE THREAD

**Issue by anhkgg** [wbond/asn1crypto#68]
in file `cryptography/src/cryptography/x509/extensions.py`, import asn1crypto
```
from asn1crypto.keys import PublicKeyInfo
```
cryptography limit asn1crypto>=0.21.0，but the newest release version has bug fixed in：
[https://github.com/wbond/asn1crypto/commit/64ab19707acb644772a9ac3d94479fbe79b49365](https://github.com/wbond/asn1crypto/commit/64ab19707acb644772a9ac3d94479fbe79b49365).

asn1crypto has not release the fixed commit.

so. when i use cryptography on Python 2, the unicode string here may raise a UnicodeDecodeError as it
tries to join a bytestring path to the unicode name "crypto"

Please  release a new version.

you can see here: https://github.com/pyca/cryptography/issues/3868#issuecomment-323349109

**Comment by ofek** [comment]
@wbond It seems all that is needed here is for you to release a new version on PyPI.

**Comment by anhkgg** [comment]
i am not so clear， i see the newest release version has not contain the fixed commit : 
https://github.com/wbond/asn1crypto/commit/64ab19707acb644772a9ac3d94479fbe79b49365

the fixed commit on 9 May, and the newest release on 15 March!

**Comment by ofek** [comment]
@anhkgg That's what I said :)

**Comment by anhkgg** [comment]
@ofek ah.

**Comment by tiran** [comment]
I talked to @wbond about a week ago. He plans to address isssue #63 first and then release a new version.

**Comment by anhkgg** [comment]
@tiran thanks! and who is him @ofek ?

**Comment by wbond** [comment]
Should be a new release soon due to all of the major outstanding issues being resolved

**Comment by wbond** [comment]
Version 0.23.0 was released last Friday.
