### ISSUE TITLE
Creating certs-only SignedData

### ISSUE THREAD

**Issue by mttcpr** [wbond/asn1crypto#71]
Trying to create a certs-only p7c, but all required fields in SignedData are not encoded, and it appears there is no way to add empty digest algorithms or signer info sets? In the absence of content, I believe both of these should be encoded as an empty SET.

      SignedData ::= SEQUENCE {
        version CMSVersion,
        digestAlgorithms DigestAlgorithmIdentifiers,
        encapContentInfo EncapsulatedContentInfo,
        certificates [0] IMPLICIT CertificateSet OPTIONAL,
        crls [1] IMPLICIT RevocationInfoChoices OPTIONAL,
        signerInfos SignerInfos }

i.e. using this code

```
    signed_data = cms.SignedData({
        'version': 'v1',
        'encap_content_info': {
            'content_type': 'data',
        },
        'certificates': cs,
    })
```

the two "SET {}" fields below are missing in the encoded output:
```

    SEQUENCE {
      INTEGER 1
      SET {}
      SEQUENCE {
        OBJECT IDENTIFIER data (1 2 840 113549 1 7 1)
        }
      [0] {
            --{ cert data here }--
        }
      SET {}
      }

```

**Comment by mttcpr** [comment]
Test code:

```
    cs = cms.CertificateSet()
    cs.append(cert)

    signed_data = cms.SignedData({
        'version': 'v1',
        'encap_content_info': {
            'content_type': 'data'
        },
        'certificates': cs,
    })

    ci = cms.ContentInfo({
        'content_type': 'signed_data',
        'content': signed_data
    })

    data = ci.dump()

```

**Comment by mttcpr** [comment]
@wbond I figured out a way to make certs-only SignedData encode the empty sets but it's probably less than  obvious for folks less familiar with DER. Maybe there's something easier I've missed.

```
    cs = cms.CertificateSet()
    cs.append(cert)

    empty_set = b'\x31\x00'
    da = cms.DigestAlgorithms.load(empty_set)
    si = cms.SignerInfos.load(empty_set)

    signed_data = cms.SignedData({
        'version': 'v1',
        'encap_content_info': {
            'content_type': 'data'
        },
        'certificates': cs,
        'digest_algorithms': da,
        'signer_infos': si
    })

    ci = cms.ContentInfo({
        'content_type': 'signed_data',
        'content': signed_data
    })

p7c_data = ci.dump()

```

**Comment by wbond** [comment]
Hoping to have a little time to look into this soon – just did the big move, and got stuck in limbo in the process. Settling back into a reasonable routine, so hopefully some open source work will be flowing shortly.

**Comment by wbond** [comment]
There is a missing error handler in the `core.Sequence.dump()` method, but this is the correct code to dump your structure:

```python
ci = cms.ContentInfo({
    'content_type': 'signed_data',
    'content': {
        'version': 'v1',
        'digest_algorithms': [],
        'encap_content_info': {
            'content_type': 'data'
        },
        'certificates': [cert],
        'signer_infos': []
    }
})
data = ci.dump()
```

**Comment by wbond** [comment]
3af3664c3b860c20d863b42d21c818cca8a43865 adds a check to ensure that all fields are included in a Sequence before it is dumped.
