### ISSUE TITLE
Issue Loading cms.SignedData

### ISSUE THREAD

**Issue by aaronst** [wbond/asn1crypto#74]
I'm having troubles trying to load a `cms.SignedData()`.

```python
#!/usr/bin/env python2


"""Test asn1crypto's cms module with a Signed Data blob."""


from asn1crypto.cms import SignedData


if __name__ == '__main__':
    F = open('test.cms', 'rb')

    SIGNED_DATA = SignedData.load(F.read())

    print '# of certs: {}'.format(len(SIGNED_DATA['certificates']))
```

[Here](https://nofile.io/f/ctDosgg1Nf4/test.cms) is a signed data blob that I'm using to test.  You can verify that it is in fact a signed data blob with the following `openssl` command:

```
openssl asn1parse -i -in test.cms -inform DER
```

Using that blob with the script above results in the following:

```
Traceback (most recent call last):
  File "./cms_test.py", line 15, in <module>
    print '# of certs: {}'.format(len(SIGNED_DATA['certificates']))
  File "/usr/local/lib/python2.7/site-packages/asn1crypto/core.py", line 3248, in __getitem__
    self._parse_children()
  File "/usr/local/lib/python2.7/site-packages/asn1crypto/core.py", line 3706, in _parse_children
    raise e
ValueError: Field "encap_content_info" is missing from structure
    while parsing asn1crypto.cms.SignedData
```

So, either I'm mistaken and the file I'm using to test isn't a signed data blob, or there is a bug in this module.  Any help is much appreciated.

Thanks

**Comment by joernheissler** [comment]
use cms.ContentInfo

**Comment by joernheissler** [comment]
Interestingly, when dump()ed, the result from asn1crypto is 2 bytes smaller than the original.
At least one of the two encoders has a bug. I'll try to look into it.

**Comment by aaronst** [comment]
@joernheissler awesome, too easy.  How did you know to use ContentInfo?  (So I don't bug you with similar questions in the future.)

**Comment by joernheissler** [comment]
Because it always is ContentInfo.
I had to learn this fact by trial+error once.

Or you have a look inside your structure and see "OBJECT IDENTIFIER signedData (1 2 840 113549 1 7 2)". You should wonder why a SignedData (that you suspect it is) explicitly contains the signedData OID. What a waste of precious space and too explicit for ASN.1. Unless it's a container format which *contains* a SignedData. And it should be obvious by the name "ContentInfo" that this is a container format ;-)

**Comment by wbond** [comment]
Thanks for helping @aaronst out, @joernheissler!
