### ISSUE TITLE
can we validate PDF signatures using this ?

### ISSUE THREAD

**Issue by sandys** [wbond/asn1crypto#76]
hi,
sorry if this is the wrong place to ask, but have been looking for a python utility to check and validate signed PDF.

You have a pdf library, but no testcases for that - so am wondering if I got the meaning wrong.

**Comment by wbond** [comment]
This library provides some of the low-level data parsing features needed for PDF signature verification, but does not deal with any of the actual PDF format details, nor the cryptographic algorithms for signature verification. The oscrypto library I wrote deals with the cryptographic part.

If you are working for a company that is interested in a Python solution for PDF verification, my company Codex Non Sufficit has a product that could be a good fit for you. You can contact me at will@codexns.io.
