### ISSUE TITLE
pypi tarball is missing tests

### ISSUE THREAD

**Issue by mgorny** [wbond/asn1crypto#83]
The tarball uploaded to pypi doesn't contain the `tests` directory. Could you please fix it to contain all files necessary to test the package?

**Comment by wbond** [comment]
No, that would add 3MB to the tarball.

**Comment by wbond** [comment]
If you are interested, you could help do some of the leg work in helping figure out how things would need to be tweaked to create an asn1crypto-tests package. See #59 for more conversation.
