### ISSUE TITLE
Problems parsing GeneralizedTime if one decimal is used

### ISSUE THREAD

**Issue by erny** [wbond/asn1crypto#86]
I receive de following string: \0x181520180405062426.0+0200
but I get error: TypeError: coercing to Unicode: need string or buffer, datetime.timedelta found

This can be fixes changing GeneralizedTime in core.py, function _date_by_len (around line 4725):
        elif strlen == 18:
to:
        elif strlen > 14:

All tests still pass.

**Comment by joernheissler** [comment]
Ok, I'll send a PR. Might take me a few days though.

**Comment by erny** [comment]
Thanks so much. @joernheissler, your patch looks great. I'll try to revoke #87.

**Comment by wbond** [comment]
@joernheissler I can create a commit with your suggested code, if you'd like

**Comment by joernheissler** [comment]
Sorry, I'm a bit busy. What I've got so far: https://github.com/joernheissler/asn1crypto/tree/time
Tests are missing, the code is mostly untested and the changes might break things in some rare situations.

**Comment by wbond** [comment]
No worries, I just figured if I ended up having a few minutes I could move it closer to the goal post.

**Comment by joernheissler** [comment]
Took me a while, sorry :-)

I ended up refactoring most of util.py to properly support time zones in the extended_datetime class.

**Comment by wbond** [comment]
Don't worry about how long it took, just **thank you** for putting in the work and figuring out the edge cases!
