### ISSUE TITLE
Have not_valid_after and not_valid_before fields on x509.Certificate

### ISSUE THREAD

**Issue by reox** [wbond/asn1crypto#93]
We recently switched at androguard from cryptography to asn1crypto.
It looks like that the Certificate class are quite compatbile but it bugs me, that you can not easily get the validity of the certificate.
In cryptography's implementation, you have the fields `not_valid_after` and `not_valid_before` which return a datetime.
I learned you can do something like this:
```
not_valid_before = x509_cert['tbs_certificate']['validity']['not_before'].native
not_valid_after = x509_cert['tbs_certificate']['validity']['not_after'].native
```

It would be nice to have the same functionality as in cryptography library!

**Comment by wbond** [comment]
Interested in sending a PR to add those, along with a few basic tests?

**Comment by reox** [comment]
As far as I understand the library this should be sufficient, right?

```
@property
def not_valid_before(self):
    return self['tbs_certificate']['validity']['not_before'].native
```

For the tests I think I need a little bit to get adjusted to your setup, but I can send a PR when I'm ready!

**Comment by joernheissler** [comment]
Feature added in https://github.com/wbond/asn1crypto/pull/94
