### ISSUE TITLE
Convert from asn1crypto.x509.Certificate to PEM, DER, CER

### ISSUE THREAD

**Issue by ftbarata** [wbond/asn1crypto#95]
Hello, I am using this function:
https://github.com/danni/python-pkcs11/blob/master/tests/test_x509.py#L166

And the result is an asn1crypto.x509.Certificate instance. How to convert it to PEM, DER, CER.... formats?

**Comment by wbond** [comment]
The docs are located at https://github.com/wbond/asn1crypto/tree/master/docs.

 - DER: https://github.com/wbond/asn1crypto/blob/master/docs/universal_types.md#basic-usage
 - PEM: https://github.com/wbond/asn1crypto/blob/master/docs/pem.md
 - CER is not supported

**Comment by ftbarata** [comment]
Hello @wbond . Thanks for reply. But, these functions expect to receive byte string and the result is an asn1crypto.x509.Certificate as I mentioned before. Could you give me a little more clue?

**Comment by ftbarata** [comment]
@wbond Thank you so much. It's working. 

I'm just curious about a thing: Take a little look at the code below. I just copied the https://github.com/danni/python-pkcs11/blob/master/tests/test_x509.py#L166 and changed the priv and pub key to be readed via pkcs11 API (usb token). I've pasted the PEM output in the https://lapo.it/asn1js/ and I don't see the trust chain of the certificate. The token I am using was issued by a CA,  so there is a trust chain, which do not appear. What am I doing wrong?

`lib = pkcs11.lib('/usr/lib/libeToken.so.9')

for slot in lib.get_slots():
    try:
        token = slot.get_token()
        with token.open(user_pin='1010') as session:
            priv = session.get_key(object_class=pkcs11.constants.ObjectClass.PRIVATE_KEY)
            pub = session.get_key(object_class=pkcs11.constants.ObjectClass.PUBLIC_KEY)

            tbs = TbsCertificate({
                'version': 'v1',
                'serial_number': 1,
                'issuer': Name.build({
                    'common_name': 'Test Certificate',
                }),
                'subject': Name.build({
                    'common_name': 'Test Certificate',
                }),
                'signature': {
                    'algorithm': 'sha256_rsa',
                    'parameters': None,
                },
                'validity': {
                    'not_before': Time({
                        'utc_time': datetime.datetime(2017, 1, 1, 0, 0),
                    }),
                    'not_after': Time({
                        'utc_time': datetime.datetime(2038, 12, 31, 23, 59),
                    }),
                },
                'subject_public_key_info': {
                    'algorithm': {
                        'algorithm': 'rsa',
                        'parameters': None,
                    },
                    'public_key': RSAPublicKey.load(encode_rsa_public_key(pub)),
                }
            })

            # Sign the TBS Certificate
            value = priv.sign(tbs.dump(),
                              mechanism=Mechanism.SHA256_RSA_PKCS)

            cert = Certificate({
                'tbs_certificate': tbs,
                'signature_algorithm': {
                    'algorithm': 'sha256_rsa',
                    'parameters': None,
                },
                'signature_value': value,
            })
            print(pem.armor('CERTIFICATE', cert.dump()).decode())`

**Comment by wbond** [comment]
This issue is closed, so this isn't the right place to ask new questions. If you post a new issue, perhaps someone will have time to go over your code and try to answer you question. Alternatively you could ask on StackOverflow.
