### ISSUE TITLE
Stuck on building an extension authority information access URI

### ISSUE THREAD

**Issue by ftbarata** [wbond/asn1crypto#96]
Hello, I'm stuck on trying to build an extension:

`authority_information_access = Extension({'extn_id': ExtensionId('1.3.6.1.5.5.7.1.1'),
'critical': False,
'extn_value': {'access_method': AccessMethod('1.3.6.1.5.5.7.48.5'), 'access_location': GeneralName(URI('http://test.com'))}
})`

I get:

`.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 1100, in __init__
    if name not in self._name_map:
TypeError: unhashable type: 'URI'
    while constructing asn1crypto.x509.GeneralName`

I tried many ways, like
`uri = URI()
uri.set(value='http://test.com')
GeneralName(uri)
`
But no success. Don't know what else to try to make it works

**Comment by mttcpr** [comment]
You can probably sort it out by looking at the certbuilder code?

https://github.com/wbond/certbuilder/blob/master/certbuilder/__init__.py#L664

**Comment by wbond** [comment]
@ftbarata In general if you aren't super familiar with ASN.1 structures and definitions, using something like certbuilder may help prevent making certain types of mistakes. That said, it is possible you are doing something certbuilder can't, but it should give you an idea of some of the parts going into generating a certificate and signing it.

**Comment by ftbarata** [comment]
@wbond , I sware I am trying hard to make it works.
` authority_information_access = Extension({'extn_id': ExtensionId('1.3.6.1.5.5.7.1.1'),
'critical': False,
'extn_value': AccessDescription({'access_method': AccessMethod('1.3.6.1.5.5.7.48.5'),
'access_location': GeneralName({'uniform_resource_identifier': 'http://test.com'})})})`

Do you mind to tell me where is the error? Or give an example?

**Comment by ftbarata** [comment]
@mttcpr , I took a look at the link you gave. So, I tried:

`authority_information_access = Extension({'extn_id': ExtensionId('1.3.6.1.5.5.7.1.1'),
 'critical': False,
 'extn_value': AccessDescription({'access_method': AccessMethod('1.3.6.1.5.5.7.48.5'),
 'access_location': GeneralName({'uniform_resource_identifier': 'http://test.com'})})})`

I tried too:

`GeneralName(name='uniform_resource_identifier', value='http://test.com')`

Both ways give:

TypeError: asn1crypto.core.ParsableOctetString value must be a byte string, not asn1crypto.x509.AccessDescription
    while constructing asn1crypto.core.ParsableOctetString
    while constructing asn1crypto.x509.Extension

It would be fantastic if there would some examples...

So, any idea?

**Comment by wbond** [comment]
@ftbarata Alright, then I would presume you are all set now that we've shown how to add the extension. If you want another example, certbuilder does it like so: https://github.com/wbond/certbuilder/blob/master/certbuilder/__init__.py#L664-L685.

**Comment by ftbarata** [comment]
Hi @wbond

**Comment by joernheissler** [comment]
@ftbarata can indent your pastes properly and put them inside triple-backticks like this:
```markdown
``​`python
foo = bar
``​`
```
(Don't copy+paste my backticks. They contain a hidden char)

**Comment by ftbarata** [comment]
Sure I can. But it's better you look at your own post at:

https://github.com/wbond/asn1crypto/issues/96#issuecomment-391019540

**Comment by joernheissler** [comment]
Not my post.
I can confirm it doesn't work. It works if you don't use the OID but the symbolic name:
```python
authority_information_access = Extension({
    'extn_id': ExtensionId('authority_information_access'),
    'critical': False,
    'extn_value': [{
        'access_method': AccessMethod('1.3.6.1.5.5.7.48.5'),
        'access_location': GeneralName('uniform_resource_identifier', URI('http://test.com'))
    }]
})
```

**Comment by ftbarata** [comment]
@joernheissler  THANK YOU SO MUCH! Now it's working!

**Comment by joernheissler** [comment]
@ftbarata bug was already fixed in 0fc0d398310e260008529329f65ba2e8efafae8e (https://github.com/wbond/asn1crypto/issues/80)

@wbond how about a new release?

**Comment by ftbarata** [comment]
Hi @joernheissler , is there another bug too?


'''
crl_distribution_point = Extension({
                                'extn_id': ExtensionId('crl_distribution_points'),
                                'critical': False,
                                'extn_value': [{
                                    'distribution_point': DistributionPointName('full_name', GeneralName('uniform_resource_identifier', URI(AUTHORITY_INFORMATION_ACCESS))),
                                    'crl_issuer': GeneralName('uniform_resource_identifier', URI(CRL_DISTRIBUTION_POINT))
                                }]
                            })
'''

Traceback (most recent call last):
  File "/home/fellipe/.pyenv/versions/3.5.4/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "agent.py", line 285, in run
    AUTHORITY_KEY_IDENTIFIER=hexadecimal_sha1_token_public_key
  File "agent.py", line 93, in createCertificateOsCrypto
    'distribution_point': DistributionPointName('full_name', GeneralName('uniform_resource_identifier', URI(AUTHORITY_INFORMATION_ACCESS))),
  File "/home/fellipe/ownCloud/feneb2/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 1122, in __init__
    raise e
  File "/home/fellipe/ownCloud/feneb2/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 1114, in __init__
    value = spec(value, **params)
  File "/home/fellipe/ownCloud/feneb2/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3913, in __init__
    raise e
  File "/home/fellipe/ownCloud/feneb2/.virtualenv/lib/python3.5/site-packages/asn1crypto/core.py", line 3903, in __init__
    for index, child in enumerate(value):
TypeError: 'GeneralName' object is not iterable
    while constructing asn1crypto.x509.GeneralNames
    while constructing asn1crypto.x509.DistributionPointName

**Comment by wbond** [comment]
@ftbarata No, there is a bug in your code. See https://github.com/wbond/asn1crypto/blob/master/asn1crypto/x509.py#L1535. The `crl_issuer` needs to be a `GeneralNames` type, but you are passing a single `GeneralName`. Notice that the spec has an `s` on the end. That type is a `SequenceOf` (https://github.com/wbond/asn1crypto/blob/master/asn1crypto/x509.py#L1458), so you'll need to pass the `GeneralName` inside of a `list`.

**Comment by wbond** [comment]
Since this issue is closed, let's move any further discussion to a new issue.
